# -*- coding: utf-8 -*-
"""Custom fields: only the fields a plan USES (a name, or a value on some task) appear in the task dialog, the Columns menu and the exports; they are added
and removed in the Manage dialog (an Add-field menu by type); the four kinds edit in the list; names belong to the plan; filters, Excel, bulk edit, sync."""
import json, os
import openpyxl
from playwright.sync_api import sync_playwright
URL = os.environ.get("MILESTONE_URL", "http://127.0.0.1:8937/milestone.html")
errors, results = [], []
def check(name, cond, detail=""):
    results.append(bool(cond)); print(("PASS  " if cond else "FAIL  ") + name + (f"   [{str(detail)[:300]}]" if not cond and detail else ""))

DEFAULT_SHOWN = ["mode", "wbs", "name", "start", "end", "actualStart", "actualFinish", "duration", "progress", "preds", "status"]
FOUR = {"text1": "Cost centre", "number1": "Budget", "date1": "Due", "flag1": "Approved"}   # the fields most sections work with (named = in use)
MK = """(specs) => { tasks.length = 0; selectedTaskId = null; colFilters = newColFilters(); filterPinned.clear();
  let n = 0; const ids = {};
  for (const sp of specs) { const t = Object.assign({id: genId(), name: sp.name, parentId: sp.parent ? ids[sp.parent] : null, order: n++, startDate: sp.s || '2026-09-07', endDate: sp.e || sp.s || '2026-09-11', progress: sp.p || 0, milestone: false, color: null, predecessors: [], collapsed: false, updatedAt: 1, constraintType: 'ASAP', constraintDate: null, taskMode: 'auto', resource: '', actualStart: null, actualFinish: null}, sp.extra || {}); tasks.push(t); ids[sp.name] = t.id; }
  currentView = 'tasks'; save(); render(); }"""

with sync_playwright() as p:
    b = p.chromium.launch(headless=True)
    ctx = b.new_context(viewport={"width": 1600, "height": 900}, accept_downloads=True); ctx.add_init_script("delete window.showOpenFilePicker; delete window.showSaveFilePicker; delete window.showDirectoryPicker")
    pg = ctx.new_page(); pg.on("pageerror", lambda e: errors.append(str(e))); pg.on("console", lambda m: errors.append(m.text) if m.type in ("error", "warning") else None)
    pg.goto(URL); pg.wait_for_selector("#addTaskBtn"); pg.evaluate("() => localStorage.clear()"); pg.reload(); pg.wait_for_selector("#addTaskBtn")
    ev = pg.evaluate
    make = lambda specs: (ev(MK, specs), pg.wait_for_timeout(100))
    head_cols = lambda: ev("() => [...document.querySelectorAll('#gridHeader .col-filter-btn')].map(b => b.dataset.col)")
    head_text = lambda col: pg.locator(f"#gridHeader .col-head:has(.col-filter-btn[data-col='{col}']) > span").text_content().strip()
    names = lambda: ev("() => visibleTaskList().map(x => x.task.name)")
    tid = lambda n: ev("n => tasks.find(t => t.name === n).id", n)
    custom = lambda n: ev("n => { const t = tasks.find(x => x.name === n); return t.custom === undefined ? 'NONE' : t.custom; }", n)
    def use(m=None):   # put fields in use by naming them (the plan's names), and show them as columns
        m = m or FOUR
        ev("(m) => { project.fieldNames = m; project.updatedAt = Date.now(); normalizeData(); save(); render(); for (const c of Object.keys(m)) colHidden.delete(c); save(); render(); }", m); pg.wait_for_timeout(100)
    def cell(name, col):
        i = head_cols().index(col)
        return pg.locator(f".grid-row[data-id='{tid(name)}']").locator(":scope > div").nth(1 + i)
    def wait_focus(): pg.wait_for_function("() => document.activeElement && document.activeElement.classList.contains('inline-edit')")
    def edit(name, col, value):
        cell(name, col).click(); pg.wait_for_selector(".inline-edit"); wait_focus()
        pg.fill(".inline-edit", value); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    def open_cols():
        if not pg.locator("#columnsMenu.open").count(): pg.click("#columnsBtn")
        pg.wait_for_selector("#columnsMenu.open")
    def close_cols(): pg.keyboard.press("Escape"); pg.wait_for_timeout(80)
    def open_dialog(n): ev("n => openTaskModal(tasks.find(t => t.name === n).id)", n); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(80)
    def close_dialog(): ev("() => closeTaskModal()"); pg.wait_for_timeout(50)
    modal_open = lambda i: ev("(i) => document.getElementById(i).classList.contains('open')", i)
    def menu_cols(): return ev("() => [...document.querySelectorAll('#columnsMenu input[data-col]')].map(i => [i.dataset.col, i.closest('label').innerText.trim(), i.checked])")

    # ================================================================= which fields are in use
    make([{"name": "One"}, {"name": "Two", "s": "2026-09-14", "e": "2026-09-18"}])
    check("a plan that uses no custom field shows none: no columns", head_cols() == DEFAULT_SHOWN, head_cols())
    open_cols(); rows = menu_cols()
    check("...the Columns menu lists no custom rows, only a link 'Add a custom field…'", not any(r[0][-1].isdigit() for r in rows) and "Add a custom field" in pg.inner_text("#columnsMenu .cols-foot"), rows[-2:])
    check("...no rename pencils any more", pg.locator("#columnsMenu .cols-rename").count() == 0); close_cols()
    open_dialog("One"); pg.click("#taskTabBtnCustom")
    check("the task dialog's Custom tab says there are none yet and offers Add field / Manage fields…", "No custom fields yet" in pg.inner_text("#taskCustomFields") and pg.locator("#cfAddBtn").is_visible() and pg.locator("#taskTabCustom .btn-link").inner_text().strip() == "Manage fields…")
    close_dialog()
    ev("() => { project.fieldNames = { text2: 'Owner' }; normalizeData(); save(); render(); }"); pg.wait_for_timeout(80)
    open_cols(); rows = menu_cols()
    check("naming a field puts it in use: the menu lists just that one (Owner, unticked)", [r for r in rows if r[0] == "text2"] == [["text2", "Owner", False]] and sum(1 for r in rows if r[0][-1].isdigit()) == 1, rows)
    check("...with a Manage link at the bottom", "Manage custom fields" in pg.inner_text("#columnsMenu .cols-foot")); close_cols()
    ev("() => { tasks[0].custom = { number3: 7 }; normalizeData(); save(); render(); }"); pg.wait_for_timeout(80)
    open_cols(); rows = menu_cols()
    check("a value puts a field in use too, under its default name (Number3)", [r for r in rows if r[0] == "number3"] == [["number3", "Number3", False]], rows); close_cols()
    ev("() => { colHidden.delete('text5'); colHidden.delete('text2'); save(); render(); }")
    check("a column this device shows but the plan does not use is not drawn (text5); one that is in use is (text2)", "text5" not in head_cols() and "text2" in head_cols(), head_cols())
    ev("() => { colOrder.splice(colOrder.indexOf('text2') + 1, 0, colOrder.splice(colOrder.indexOf('number3'), 1)[0]); colHidden.delete('number3'); save(); render(); renderColumnsMenu(); }")
    open_cols()
    pg.locator("#columnsMenu .cols-row:has(input[data-col='number3']) .cols-move button").first.click(); pg.wait_for_timeout(100)
    check("moving a column skips the custom fields the menu does not list (Number3 moves above Owner in one click)", head_cols().index("number3") < head_cols().index("text2"), head_cols()); close_cols()
    ev("() => { delete project.fieldNames; delete tasks[0].custom; normalizeData(); save(); render(); }"); pg.wait_for_timeout(80)
    check("taking the name and the value away puts the fields out of use again", "text2" not in head_cols() and "number3" not in head_cols() and ev("() => activeCustomFields().length") == 0)

    # ================================================================= editing in the list
    make([{"name": "One"}, {"name": "Two", "s": "2026-09-14", "e": "2026-09-18"}]); use()
    edit("One", "text1", "  Hello world  ")
    check("Text: click, type, Enter -> saved (trimmed) on the task", custom("One") == {"text1": "Hello world"} and cell("One", "text1").inner_text().strip() == "Hello world", custom("One"))
    check("...the change is stamped so it syncs", ev("() => tasks.find(t => t.name === 'One').updatedAt > 1"))
    cell("One", "text1").click(); wait_focus(); pg.fill(".inline-edit", "NOPE"); pg.keyboard.press("Escape"); pg.wait_for_timeout(80)
    check("Escape cancels a text edit", custom("One") == {"text1": "Hello world"})
    cell("One", "text1").click(); wait_focus(); check("the text editor allows up to 255 characters", pg.get_attribute(".inline-edit", "maxlength") == "255"); pg.keyboard.press("Escape")
    edit("One", "text1", "<b>bold?</b> & \"quotes\"")
    check("text is shown literally, never as markup", cell("One", "text1").inner_text().strip() == '<b>bold?</b> & "quotes"' and pg.locator(".grid-row b").count() == 0)
    edit("One", "number1", "12,5")
    check("Number: a comma decimal is accepted (12,5 -> 12.5) and shown", custom("One")["number1"] == 12.5 and cell("One", "number1").inner_text().strip() == "12.5", custom("One"))
    edit("One", "number1", "abc")
    check("...text in a number field is refused (toast, nothing changes)", custom("One")["number1"] == 12.5 and "isn't a number" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    edit("One", "number1", "0"); check("...0 is a value (not empty)", custom("One")["number1"] == 0 and cell("One", "number1").inner_text().strip() == "0")
    cell("One", "date1").click(); pg.wait_for_selector(".inline-edit"); wait_focus()
    check("Date: opens a native date editor", pg.get_attribute(".inline-edit", "type") == "date")
    pg.fill(".inline-edit", "2026-12-24"); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    check("...saved as an ISO date and shown dd.mm.yyyy", custom("One")["date1"] == "2026-12-24" and cell("One", "date1").inner_text().strip() == "24.12.2026")
    cell("One", "flag1").click(); pg.wait_for_timeout(80)
    check("Flag: one click sets it (a tick appears), stored as true", custom("One")["flag1"] is True and cell("One", "flag1").locator("i.fa-check").count() == 1 and pg.locator(".inline-edit").count() == 0)
    cell("One", "flag1").click(); pg.wait_for_timeout(80)
    check("...another click clears it", "flag1" not in custom("One") and cell("One", "flag1").locator("i").count() == 0)
    for col, val in (("text1", ""), ("number1", ""), ("date1", "")): edit("One", col, val)
    check("clearing every value removes the task's custom object altogether (no empty leftovers)", custom("One") == "NONE", custom("One"))
    check("...and a named field stays in use with no value anywhere", ev("() => activeCustomFields().length") == 4)
    make([{"name": "Grp"}, {"name": "Kid", "parent": "Grp"}, {"name": "MS", "extra": {"milestone": True}}]); use()
    edit("Grp", "text1", "group note"); cell("MS", "flag1").click(); pg.wait_for_timeout(60); edit("MS", "text1", "milestone note")
    check("groups and milestones can have custom values too (nothing is rolled up)", custom("Grp") == {"text1": "group note"} and custom("MS") == {"flag1": True, "text1": "milestone note"} and custom("Kid") == "NONE")
    check("a new task has no custom object", ev("() => { addTask(); const t = tasks[tasks.length - 1]; const r = !('custom' in t); closeTaskModal(); return r; }"))

    # ================================================================= the dialog's Custom tab
    make([{"name": "Alpha", "extra": {"custom": {"text2": "hello", "number3": 7.25, "date4": "2026-10-01", "flag5": True}}}, {"name": "Beta"}])
    ev("() => { delete project.fieldNames; normalizeData(); save(); render(); }")   # (the earlier sections named some fields: this one works with values alone)
    open_dialog("Alpha")
    check("dialog: two tabs, General (active) and Custom fields, with a badge of the task's values (4)", pg.locator("#taskModalBg .modal-tab").all_inner_texts()[0].strip() == "General" and pg.inner_text("#taskCustomBadge").strip() == "4", pg.inner_text("#taskCustomBadge"))
    pg.click("#taskTabBtnCustom")
    labels = ev("() => [...document.querySelectorAll('#taskCustomFields .cf-label > span, #taskCustomFields .cf-flag label span')].map(e => e.innerText.trim())")
    check("the tab shows ONLY the four fields in use (by value here: Text2, Number3, Date4, Flag5), not twenty", labels == ["Text2", "Number3", "Date4", "Flag5"], labels)
    check("...text / number / date fields in a two-column grid, the flag as a tick below; no rename pencils", pg.locator("#taskCustomFields .cf-grid .field").count() == 3 and pg.locator("#taskCustomFields .cf-flags input[type=checkbox]").count() == 1 and pg.locator(".cf-rename").count() == 0)
    check("...the task's values are filled in", pg.input_value("#cf_text2") == "hello" and pg.input_value("#cf_number3") == "7.25" and pg.input_value("#cf_date4") == "2026-10-01" and pg.is_checked("#cf_flag5"))
    check("...it fits the dialog without scrolling", ev("() => { const b = document.querySelector('#taskModalBg .modal-body'); return b.scrollHeight <= b.clientHeight + 1; }"))
    pg.fill("#cf_text2", "changed"); pg.fill("#cf_number3", "9"); pg.uncheck("#cf_flag5")
    check("the badge follows what is typed (4 -> 3)", pg.inner_text("#taskCustomBadge").strip() == "3", pg.inner_text("#taskCustomBadge"))
    pg.click("#taskTabBtnGeneral"); pg.fill("#taskNameInput", "Alpha renamed"); pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(150)
    check("Save from any tab saves both: the General edit and the custom values", custom("Alpha renamed") == {"text2": "changed", "number3": 9, "date4": "2026-10-01"}, custom("Alpha renamed"))
    open_dialog("Beta"); pg.click("#taskTabBtnCustom"); pg.fill("#cf_text2", "   "); pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(120)
    check("whitespace-only text isn't a value", custom("Beta") == "NONE", custom("Beta"))
    open_dialog("Beta"); pg.click("#taskTabBtnGeneral"); pg.fill("#taskActualStartInput", "2026-09-20"); pg.fill("#taskActualFinishInput", "2026-09-10")
    pg.click("#taskTabBtnCustom"); pg.fill("#cf_text2", "x"); pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(150)
    check("a validation error on the General tab, hit when saving from the Custom tab, switches back to General and keeps the dialog open", modal_open("taskModalBg") and pg.locator("#taskTabGeneral").is_visible())
    close_dialog()

    # ================================================================= adding fields: the Add-field menu and the Manage dialog
    make([{"name": "Solo", "extra": {"custom": {"text1": "keep"}}}, {"name": "Other"}])
    ev("() => { project.fieldNames = {}; delete project.fieldNames; normalizeData(); }")
    open_dialog("Other"); pg.click("#taskTabBtnCustom"); pg.fill("#cf_text1", "typed, not saved"); pg.click("#cfAddBtn"); pg.wait_for_timeout(120)
    items = pg.locator("#cfAddMenu .dropdown-item").all_inner_texts()
    check("'Add field' opens a menu by type (Text, Number, Date, Yes / No) — above the dialog", len(items) == 4 and [i.split("\n")[0].strip() for i in items] == ["Text", "Number", "Date", "Yes / No"] and ev("() => { const r = document.getElementById('cfAddMenu').getBoundingClientRect(); return document.elementFromPoint(r.left + 20, r.top + 20).closest('#cfAddMenu') !== null; }"), items)
    pg.click("#cfAddMenu .dropdown-item:has-text('Number')"); pg.wait_for_selector("#fieldsModalBg.open"); pg.wait_for_timeout(200)
    check("choosing a type opens the Manage dialog on top of the task dialog, with a new empty Number row focused", ev("() => document.activeElement.classList.contains('fld-name') && document.activeElement.value === ''") and pg.locator("#fieldsRows .fld-row").count() == 2 and "Number" in pg.locator("#fieldsRows .fld-row").last.inner_text())
    check("...the existing field (Text1, in use by a value) is listed with its use ('1 task')", "1 task" in pg.locator("#fieldsRows .fld-row").first.inner_text() and pg.locator("#fieldsRows .fld-name").first.input_value() == "Text1")
    pg.keyboard.press("Enter"); pg.wait_for_timeout(120)
    check("saving a new field without a name is refused (message, box marked, dialog stays)", "Give the new field a name" in pg.inner_text("#toastMsg") and modal_open("fieldsModalBg") and pg.locator("#fieldsRows .fld-name.bad").count() == 1)
    pg.fill("#fieldsRows .fld-row:last-child .fld-name", "Start"); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    check("...so is the name of a standard column (Start)", "already the name" in pg.inner_text("#toastMsg") and modal_open("fieldsModalBg"))
    pg.fill("#fieldsRows .fld-row:last-child .fld-name", "Text3"); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    check("...and the default name of an unused field (Text3)", "reserved" in pg.inner_text("#toastMsg") and modal_open("fieldsModalBg"))
    pg.fill("#fieldsRows .fld-row:last-child .fld-name", "text1"); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    check("...and another field's name, case-insensitively (text1 = Text1)", "already the name" in pg.inner_text("#toastMsg") and modal_open("fieldsModalBg"))
    pg.fill("#fieldsRows .fld-row:last-child .fld-name", "  Budget  "); pg.keyboard.press("Enter"); pg.wait_for_timeout(200)
    check("a good name saves: the field is in use under the trimmed name, on the plan", ev("() => project.fieldNames") == {"number1": "Budget"} and not modal_open("fieldsModalBg"), ev("() => project.fieldNames"))
    check("...the task dialog stays open on the Custom tab, shows the new field and keeps what was typed", modal_open("taskModalBg") and pg.locator("#taskTabCustom").is_visible() and pg.input_value("#cf_number1") == "" and pg.input_value("#cf_text1") == "typed, not saved")
    pg.click("#taskModalBg .modal-header button"); pg.wait_for_timeout(200)
    check("...and adding a field is not counted as a change: × still asks because of the typed text, not the new box", modal_open("confirmModalBg")); pg.click("#confirmModalActionBtn"); pg.wait_for_timeout(200)
    open_dialog("Other"); pg.click("#taskModalBg .modal-header button"); pg.wait_for_timeout(200)
    check("a fresh dialog with the new field closes with × without a question", not modal_open("taskModalBg") and not modal_open("confirmModalBg"))
    # the Manage dialog itself
    open_dialog("Other"); pg.click("#taskTabBtnCustom"); pg.click("#taskTabCustom .btn-link"); pg.wait_for_selector("#fieldsModalBg.open"); pg.wait_for_timeout(150)
    pg.click("#fieldsAddBtn"); pg.click("#cfAddMenu .dropdown-item:has-text('Yes / No')"); pg.wait_for_timeout(120); pg.keyboard.type("Approved")
    pg.click("#fieldsAddBtn"); pg.click("#cfAddMenu .dropdown-item:has-text('Date')"); pg.wait_for_timeout(120); pg.keyboard.type("Due")
    pg.keyboard.press("Enter"); pg.wait_for_timeout(200)
    check("the Manage dialog adds several fields in one go (Approved as a flag, Due as a date)", ev("() => project.fieldNames") == {"number1": "Budget", "flag1": "Approved", "date1": "Due"}, ev("() => project.fieldNames"))
    pg.click("#taskTabBtnCustom"); labels = ev("() => [...document.querySelectorAll('#taskCustomFields .cf-label > span, #taskCustomFields .cf-flag label span')].map(e => e.innerText.trim())")
    check("...they appear in the tab in the canonical order (Text1 has a value; Budget, Due, then the flag Approved)", labels == ["Text1", "Budget", "Due", "Approved"], labels); close_dialog()
    # rename, remove with values, undo
    ev("() => { tasks.find(t => t.name === 'Solo').custom = { number1: 5, flag1: true }; tasks.find(t => t.name === 'Other').custom = { number1: 6 }; save(); render(); }")
    ev("() => openFieldsModal()"); pg.wait_for_selector("#fieldsModalBg.open"); pg.wait_for_timeout(150)
    rows = ev("() => [...document.querySelectorAll('#fieldsRows .fld-row')].map(r => [r.querySelector('.fld-kind').innerText.trim(), r.querySelector('.fld-name').value, r.querySelector('.fld-uses').innerText.trim()])")
    check("Manage lists the fields with kind, name and how many tasks use each", rows == [["Number", "Budget", "2 tasks"], ["Date", "Due", "—"], ["Yes / No", "Approved", "1 task"]], rows)
    pg.fill("#fieldsRows .fld-row:first-child .fld-name", "Budget (EUR)"); pg.locator("#fieldsRows .fld-row").nth(2).locator(".fld-remove").click(); pg.wait_for_timeout(100)
    check("removing marks the row (struck through, restorable) and says how many will be removed", "removed" in (pg.locator("#fieldsRows .fld-row").nth(2).get_attribute("class") or "") and "1 field will be removed" in pg.inner_text("#fieldsNote"))
    pg.locator("#fieldsRows .fld-row").nth(2).locator(".fld-remove").click(); pg.wait_for_timeout(80)
    check("...the same button restores it", "removed" not in (pg.locator("#fieldsRows .fld-row").nth(2).get_attribute("class") or "") and pg.inner_text("#fieldsNote").strip() == "")
    pg.locator("#fieldsRows .fld-row").nth(2).locator(".fld-remove").click(); pg.click("#fieldsModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("saving a removal that has values asks first, naming the field and the number of tasks", modal_open("confirmModalBg") and "Approved" in pg.inner_text("#confirmModalBody") and "1 task" in pg.inner_text("#confirmModalBody") and pg.inner_text("#confirmModalActionBtn") == "Remove", pg.inner_text("#confirmModalBody"))
    pg.click("#confirmModalActionBtn"); pg.wait_for_timeout(250)
    check("confirmed: the rename applied, the flag's name and its values are gone, the field is out of use", ev("() => project.fieldNames") == {"number1": "Budget (EUR)", "date1": "Due"} and custom("Solo") == {"number1": 5} and "flag1" not in ev("() => activeCustomFields()"), (ev("() => project.fieldNames"), custom("Solo")))
    ev("() => historyUndo()"); pg.wait_for_timeout(200)
    check("Undo (Ctrl+Z) brings the field, its name and its values back", ev("() => project.fieldNames.flag1") == "Approved" and custom("Solo") == {"number1": 5, "flag1": True} and ev("() => project.fieldNames.number1") == "Budget", (ev("() => project.fieldNames"), custom("Solo")))
    ev("() => historyRedo()"); pg.wait_for_timeout(150)
    ev("() => openFieldsModal()"); pg.wait_for_selector("#fieldsModalBg.open"); pg.fill("#fieldsRows .fld-row:first-child .fld-name", "Changed"); pg.click("#fieldsModalBg .modal-header button"); pg.wait_for_timeout(200)
    check("× after a change asks 'Discard your changes?'; Escape on that question keeps editing", modal_open("confirmModalBg") and "custom fields" in pg.inner_text("#confirmModalBody"))
    pg.keyboard.press("Escape"); pg.wait_for_timeout(200)
    check("...Manage stays open with the edit", modal_open("fieldsModalBg") and not modal_open("confirmModalBg") and pg.locator("#fieldsRows .fld-name").first.input_value() == "Changed")
    pg.click("#fieldsModalBg .modal-footer .btn:has-text('Cancel')"); pg.wait_for_timeout(200)
    check("Cancel discards without asking", not modal_open("fieldsModalBg") and not modal_open("confirmModalBg") and ev("() => project.fieldNames.number1") == "Budget (EUR)")
    ev("() => openTaskModal(tasks.find(t => t.name === 'Other').id)"); pg.wait_for_selector("#taskModalBg.open"); pg.click("#taskTabBtnCustom"); pg.click("#taskTabCustom .btn-link"); pg.wait_for_selector("#fieldsModalBg.open"); pg.keyboard.press("Escape"); pg.wait_for_timeout(200)
    check("Escape in an untouched Manage dialog closes only that dialog — the task dialog stays", not modal_open("fieldsModalBg") and modal_open("taskModalBg")); close_dialog()
    # five per type
    make([{"name": "Cap"}]); ev("() => { delete project.fieldNames; normalizeData(); }")
    ev("() => openFieldsModal()"); pg.wait_for_selector("#fieldsModalBg.open")
    for i in range(5): pg.click("#fieldsAddBtn"); pg.click("#cfAddMenu .dropdown-item:has-text('Text')"); pg.wait_for_timeout(60); pg.keyboard.type(f"T{i}")
    pg.click("#fieldsAddBtn")
    check("at most five fields per type: the Text entry of the menu is disabled ('all 5 in use'), the others are not", pg.locator("#cfAddMenu .dropdown-item").first.is_disabled() and "all 5 in use" in pg.locator("#cfAddMenu .dropdown-item").first.inner_text() and not pg.locator("#cfAddMenu .dropdown-item").nth(1).is_disabled())
    pg.keyboard.press("Escape"); pg.wait_for_timeout(100)
    check("Escape closes the menu first (and only the menu)", modal_open("fieldsModalBg") and not ev("() => document.getElementById('cfAddMenu').classList.contains('open')"))
    pg.click("#fieldsModalBg .modal-footer .btn:has-text('Cancel')"); pg.wait_for_timeout(200)
    # names are user text: escaped
    ev("() => { project.fieldNames = { text1: '<img src=x onerror=window.__pwned=1>' }; normalizeData(); colHidden.delete('text1'); save(); render(); }"); pg.wait_for_timeout(100)
    open_cols()
    check("a name with markup is plain text in the header, the Columns menu, the Manage dialog and the dialog tab — never executed", head_text("text1") == "<img src=x onerror=window.__pwned=1>" and pg.locator("#gridHeader img, #columnsMenu img").count() == 0 and ev("() => window.__pwned") is None); close_cols()
    ev("() => openFieldsModal()"); pg.wait_for_selector("#fieldsModalBg.open")
    check("...(Manage)", pg.locator("#fieldsRows img").count() == 0 and pg.locator("#fieldsRows .fld-name").first.input_value() == "<img src=x onerror=window.__pwned=1>"); pg.click("#fieldsModalBg .modal-footer .btn:has-text('Cancel')"); pg.wait_for_timeout(150)

    # ================================================================= names belong to the plan
    make([{"name": "R1", "extra": {"custom": {"text1": "a", "number1": 5}}}]); use({"text1": "Cost centre", "flag1": "Approved"})
    check("plan A has its names", head_text("text1") == "Cost centre" and head_text("flag1") == "Approved")
    check("the names are stored on the plan (project.fieldNames), not in the device preferences, and the payload carries them", ev("() => project.fieldNames") == {"text1": "Cost centre", "flag1": "Approved"} and "Cost centre" not in json.dumps(ev("() => JSON.parse(localStorage.getItem('milestone-prefs'))")) and ev("() => syncPayload().project.fieldNames.text1") == "Cost centre")
    ev("() => { switchPlan(createPlanRecord('Plan B', null)); }"); pg.wait_for_timeout(500)
    check("a second plan uses no custom field (whatever this device shows): no custom columns", not any(c[-1].isdigit() for c in head_cols()) and ev("() => project.fieldNames") is None, head_cols())
    use({"text1": "Owner"})
    check("...and can name the same field differently", head_text("text1") == "Owner")
    ev("() => { const id = JSON.parse(localStorage.getItem('milestone-plans')).plans.find(p => p.name === 'My Project').id; switchPlan(id); }"); pg.wait_for_timeout(500)
    check("switching back: plan A keeps ITS names", head_text("text1") == "Cost centre" and head_text("flag1") == "Approved")
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(200)
    check("...and both survive a reload", head_text("text1") == "Cost centre")

    # ================================================================= filters
    make([{"name": "F1", "extra": {"custom": {"text1": "alpha", "number1": 5, "date1": "2026-09-30", "flag1": True}}}, {"name": "F2", "extra": {"custom": {"text1": "beta", "number1": 20, "date1": "2026-12-01"}}}, {"name": "F3", "extra": {"custom": {"text1": "alphabet", "number1": 12, "flag1": True}}}, {"name": "F4"}]); use()
    def flt(col): pg.locator(f".col-filter-btn[data-col='{col}']").click(); pg.wait_for_selector("#filterMenu.open")
    def clear(): ev("() => { colFilters = newColFilters(); render(); }")
    flt("text1"); labels = pg.locator("#filterTree .ft-label").all_inner_texts()
    check("Text filter: a value list (with (Blanks)) under the field's own name", labels == ["(Select All)", "alpha", "alphabet", "beta", "(Blanks)"] and "Filter Cost centre" in pg.inner_text("#filterMenu .filter-head"), labels)
    pg.select_option("#filterRuleSel", "begins"); pg.fill("#filterInputA", "alph"); pg.click("#filterOkBtn"); pg.wait_for_timeout(100)
    check("...'begins with alph' -> F1 and F3, chip carries the custom name", set(names()) == {"F1", "F3"} and "Cost centre: begins with" in pg.inner_text("#filterBar"), names()); clear()
    flt("number1"); pg.select_option("#filterRuleSel", "between"); pg.fill("#filterInputA", "10"); pg.fill("#filterInputB", "25"); pg.click("#filterOkBtn"); pg.wait_for_timeout(100)
    check("Number filter: between 10 and 25 -> F2 and F3", set(names()) == {"F2", "F3"}, names()); clear()
    flt("date1"); pg.select_option("#filterRuleSel", "before"); pg.fill("#filterInputA", "2026-10-15"); pg.click("#filterOkBtn"); pg.wait_for_timeout(100)
    check("Date filter: before 15.10.2026 -> F1 only", set(names()) == {"F1"}, names()); clear()
    flt("flag1"); labels = pg.locator("#filterTree .ft-label").all_inner_texts()
    check("Flag filter: a Yes / No list, Yes first, no rule selector", labels == ["(Select All)", "Yes", "No"] and pg.locator("#filterRuleSel").count() == 0, labels)
    pg.locator("#filterTree .ft-cb[data-key='all']").uncheck(); pg.locator("#filterTree .ft-label:has-text('Yes') .ft-cb").check(); pg.click("#filterOkBtn"); pg.wait_for_timeout(100)
    check("...only the flagged tasks; chip 'Approved: Yes'", set(names()) == {"F1", "F3"} and "Approved: Yes" in pg.inner_text("#filterBar"), names()); clear()
    ev("() => { colFilters.flag1 = { type: 'values', values: new Set(['Yes']), blanks: false }; render(); openFieldsModal(); }"); pg.wait_for_selector("#fieldsModalBg.open")
    pg.locator("#fieldsRows .fld-row").last.locator(".fld-remove").click(); pg.click("#fieldsModalBg .btn-primary"); pg.wait_for_timeout(150); pg.click("#confirmModalActionBtn"); pg.wait_for_timeout(250)
    check("removing a field also drops a filter on it (no invisible filter left)", ev("() => colFilters.flag1") is None and len(names()) == 4, names()); clear()

    # ================================================================= Excel
    def export(cols, path):
        pg.click("#dataMenuBtn"); pg.click("#excelExportItem"); pg.wait_for_selector("#excelModalBg.open")
        if cols != "shown": pg.check(f"input[name='excelCols'][value='{cols}']")
        pg.set_checked("#excelGantt", False)
        with pg.expect_download() as dl: pg.click("#excelExportBtn")
        dl.value.save_as(path)
    make([{"name": "X1", "extra": {"custom": {"text1": "alpha", "number1": 5.5, "date1": "2026-09-30", "flag1": True}}}, {"name": "X2", "extra": {"custom": {"text1": "beta", "number1": 20}}}])
    use({"text1": "Cost & <centre>", "number1": "Budget", "date1": "Due", "flag1": "Approved"})
    export("shown", "cf_shown.xlsx"); ws = openpyxl.load_workbook("cf_shown.xlsx")["Tasks"]; hdr = [c.value for c in ws[4]]
    check("Excel 'as shown': the custom columns follow the list, headed with the plan's names", hdr[-4:] == ["Cost & <centre>", "Budget", "Due", "Approved"], hdr)
    col = {h: i + 1 for i, h in enumerate(hdr)}
    check("Excel: Text as text, Number as a real number, Date as a real date, Flag as Yes/No; an empty value is an empty cell", ws.cell(5, col["Cost & <centre>"]).value == "alpha" and ws.cell(5, col["Budget"]).value == 5.5 and str(ws.cell(5, col["Due"]).value)[:10] == "2026-09-30" and ws.cell(5, col["Approved"]).value == "Yes" and ws.cell(6, col["Due"]).value is None)
    ev("() => { for (const c of ['text1','number1','date1','flag1']) colHidden.add(c); save(); render(); }")
    export("shown", "cf_hidden.xlsx"); h2 = [c.value for c in openpyxl.load_workbook("cf_hidden.xlsx")["Tasks"][4]]
    check("hidden custom columns are not exported in 'as shown'", not any(x in h2 for x in ("Budget", "Due", "Approved")), h2)
    export("all", "cf_all.xlsx"); h3 = [c.value for c in openpyxl.load_workbook("cf_all.xlsx")["Tasks"][4]]
    check("'All columns' adds only the fields in use — not the 16 others", [x for x in h3 if x in ("Cost & <centre>", "Budget", "Due", "Approved")] == ["Cost & <centre>", "Budget", "Due", "Approved"] and not any(str(x).startswith(("Text", "Number", "Flag")) for x in h3), h3)
    ev("() => { project.fieldNames = { text5: 'Empty but named' }; tasks.forEach(t => delete t.custom); normalizeData(); save(); render(); }")
    export("all", "cf_named.xlsx"); h4 = [c.value for c in openpyxl.load_workbook("cf_named.xlsx")["Tasks"][4]]
    check("...a named field is included even with no values", "Empty but named" in h4, h4)

    # ================================================================= bulk edit
    make([{"name": "B1"}, {"name": "B2"}]); use({"text1": "Cost centre", "flag1": "Approved"})
    ev("() => { setSelection(tasks.map(t => t.id)); render(); openBulkModal(); }"); pg.wait_for_timeout(250)
    check("bulk edit offers the custom fields that are shown columns, under their names", "Cost centre" in pg.inner_text("#bulkModalBg") and "Approved" in pg.inner_text("#bulkModalBg") and "Text2" not in pg.inner_text("#bulkModalBg"))
    pg.fill("#bulkVal-text1", "Ops"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(200)
    check("...and applies them", custom("B1") == {"text1": "Ops"} and custom("B2") == {"text1": "Ops"})

    # ================================================================= data hygiene, sync
    ev("""() => { project.fieldNames = {text1: '  Trimmed  ', bogus: 'x', number1: 5, date1: 'Date1', flag1: 'y'.repeat(60)}; tasks[0].custom = {text1: '  spaced  ', text2: 'z'.repeat(400), number1: '3,5', number2: 'NaN', number3: Infinity, date1: '2026-02-30', date2: '2026-03-04', flag1: 'true', flag2: false, bogus: 1}; tasks[1].custom = 'nope'; normalizeData(); }""")
    c0 = ev("() => tasks[0].custom")
    check("normalisation of stored values: only real fields with valid values survive", c0 == {"text1": "spaced", "text2": "z" * 255, "number1": 3.5, "date2": "2026-03-04", "flag1": True}, c0)
    check("...a custom that isn't an object is dropped", ev("() => 'custom' in tasks[1]") is False)
    fn = ev("() => project.fieldNames")
    check("normalisation of the names: unknown ids, non-strings and default names dropped, trimmed and capped at 40", fn == {"text1": "Trimmed", "flag1": "y" * 40}, fn)
    ev("() => { project.fieldNames = {}; normalizeData(); }")
    check("an empty name map is removed rather than stored", ev("() => 'fieldNames' in project") is False)
    ev("""() => { project.fieldNames = {text1: 'Old name'}; project.updatedAt = 10; const t = tasks[0]; t.updatedAt = 10; t.custom = {text1: 'old'}; }""")
    ev("""() => { const remote = {project: Object.assign({}, project, {fieldNames: {text1: 'Renamed remotely'}, updatedAt: 99}), tasks: [Object.assign({}, JSON.parse(JSON.stringify(tasks[0])), {custom: {text1: 'remote value', flag3: true}, updatedAt: 99})], deletedTaskIds: []}; mergeData(remote); normalizeData(); }""")
    check("a newer copy from another device brings its custom values and its field names with it", ev("() => [tasks[0].custom, project.fieldNames]") == [{"text1": "remote value", "flag3": True}, {"text1": "Renamed remotely"}], ev("() => [tasks[0].custom, project.fieldNames]"))
    ev("""() => { const remote = {project: Object.assign({}, project, {fieldNames: {text1: 'STALE'}, updatedAt: 1}), tasks: [Object.assign({}, JSON.parse(JSON.stringify(tasks[0])), {custom: {text1: 'stale'}, updatedAt: 1})], deletedTaskIds: []}; mergeData(remote); normalizeData(); }""")
    check("...and an older copy does not overwrite them", ev("() => [tasks[0].custom.text1, project.fieldNames.text1]") == ["remote value", "Renamed remotely"])
    check("exports, backups and the plan's file all carry both (syncPayload)", ev("() => { const s = syncPayload(); return [s.tasks[0].custom, s.project.fieldNames]; }") == [{"text1": "remote value", "flag3": True}, {"text1": "Renamed remotely"}])
    ev("""() => { pendingImportData = {project: {name: 'Imported', updatedAt: 1, fieldNames: {date2: 'Deadline'}}, tasks: [Object.assign({}, JSON.parse(JSON.stringify(tasks[0])), {custom: {date2: '2026-05-05'}})], deletedTaskIds: []}; applyImport('replace'); }""")
    check("Import → Replace restores both the values and the names", ev("() => [tasks[0].custom, project.fieldNames]") == [{"date2": "2026-05-05"}, {"date2": "Deadline"}], ev("() => [tasks[0].custom, project.fieldNames]"))

    # ================================================================= reordering and reset
    make([{"name": "Solo"}]); use({"text1": "Alpha", "text2": "Beta"})
    open_cols(); pg.locator("#columnsMenu .cols-row:has(input[data-col='text2']) .cols-move button").first.click(); pg.wait_for_timeout(100)
    check("custom columns can be reordered like any other (Beta moved above Alpha)", head_cols().index("text2") < head_cols().index("text1"), head_cols())
    pg.click("#columnsMenu .btn-link:has-text('Reset')"); pg.wait_for_timeout(100)
    check("'Reset to default' hides them again and restores the order — but keeps the plan's names", head_cols() == DEFAULT_SHOWN and ev("() => project.fieldNames") == {"text1": "Alpha", "text2": "Beta"}, head_cols())
    check("the Columns menu's link opens the Manage dialog", (pg.click("#columnsMenu .cols-foot .btn-link"), pg.wait_for_selector("#fieldsModalBg.open"), True)[2] and not ev("() => document.getElementById('columnsMenu').classList.contains('open')"))
    pg.wait_for_timeout(120)
    check("...with the cursor in the first name field", ev("() => document.activeElement.classList.contains('fld-name')")); pg.keyboard.press("Escape"); pg.wait_for_timeout(150)
    pg.click("#planMenuBtn"); pg.click("#planNewItem"); pg.wait_for_selector("#planModalBg.open"); pg.wait_for_timeout(200)
    check("New plan: the cursor is in the name field, selected", ev("() => document.activeElement.id") == "planNameInput" and ev("() => { const i = document.activeElement; return i.selectionStart === 0 && i.selectionEnd === i.value.length; }"))
    pg.keyboard.press("Escape"); pg.wait_for_timeout(100)
    ev("() => { resetColumns(); }"); open_cols()
    order = ev("() => [...document.querySelectorAll('#columnsMenu input[data-col]')].map(i => i.dataset.col)")
    check("the default column sequence: standard columns first, then the custom fields in use", order[:13] == ["mode", "wbs", "name", "start", "end", "actualStart", "actualFinish", "duration", "progress", "preds", "remaining", "status", "resource"] and order[-2:] == ["text1", "text2"], order)
    close_cols()

    check("no console errors", not errors, errors[:5])
    print("console errors/warnings:", errors); print(f"{sum(results)}/{len(results)} passed"); b.close()
