from playwright.sync_api import sync_playwright
import os
URL = os.environ.get("MILESTONE_URL", "http://127.0.0.1:8937/milestone.html")
errors, results = [], []
def check(name, cond, detail=""):
    results.append(bool(cond)); print(("PASS  " if cond else "FAIL  ") + name + (f"   [{str(detail)[:500]}]" if not cond and detail else ""))

# spec: name, parent (name), s, e, extra, preds=[[name,type,lag]]
SEED = """(specs) => { tasks.length = 0; deletedTaskIds.length = 0; setSelection([]); colFilters = newColFilters(); filterPinned.clear(); delete project.workDays; delete project.holidays;
  const ids = {}, ord = {};
  for (const sp of specs) { const k = sp.parent || ''; ord[k] = ord[k] || 0;
    const t = Object.assign({id: genId(), name: sp.name, parentId: null, order: ord[k]++, startDate: sp.s || '2026-09-07', endDate: sp.e || sp.s || '2026-09-08', progress: 0, milestone: false, color: null, predecessors: [], collapsed: false, updatedAt: 1, constraintType: 'ASAP', constraintDate: null, taskMode: 'auto', resource: '', actualStart: null, actualFinish: null}, sp.extra || {});
    tasks.push(t); ids[sp.name] = t.id; }
  for (const sp of specs) { const t = tasks.find(x => x.name === sp.name); if (sp.parent) t.parentId = ids[sp.parent]; if (sp.preds) t.predecessors = sp.preds.map(([n, type, lag]) => ({id: ids[n], type, lag})); }
  currentView = 'tasks'; normalizeData(); save(); render(); resetHistory(); }"""
FIVE = [{"name": "A"}, {"name": "B"}, {"name": "C"}, {"name": "D"}, {"name": "E"}]

with sync_playwright() as p:
    b = p.chromium.launch(headless=True)
    ctx = b.new_context(viewport={"width": 1600, "height": 900}); ctx.add_init_script("delete window.showOpenFilePicker; delete window.showSaveFilePicker")
    pg = ctx.new_page(); pg.on("pageerror", lambda e: errors.append(str(e))); pg.on("console", lambda m: errors.append(m.text) if m.type in ("error", "warning") else None)
    pg.goto(URL); pg.wait_for_selector("#addTaskBtn"); pg.evaluate("() => localStorage.clear()"); pg.reload(); pg.wait_for_selector("#addTaskBtn")
    ev = pg.evaluate
    ev("() => { historyCoalesceMs = 0; }")
    seed = lambda specs: ev(SEED, specs)
    tid = lambda n: ev("n => (tasks.find(t => t.name === n) || {}).id", n)
    sel = lambda: ev("() => selectedIds().map(id => byId(id).name)")
    row = lambda n: pg.locator(f".grid-row[data-id='{tid(n)}'] > div").first   # the ID cell: a click there selects, it never starts an edit
    click = lambda n, mods=None: row(n).click(modifiers=mods or [])
    dates = lambda n: ev("n => { const t = tasks.find(x => x.name === n); return [t.startDate, t.endDate]; }", n)
    names = lambda parent=None: ev("p => childrenOf(p).map(t => t.name)", parent)
    clip_copy = lambda: ev("() => { const dt = new DataTransfer(); const e = new ClipboardEvent('copy', { clipboardData: dt, bubbles: true, cancelable: true }); document.body.dispatchEvent(e); return { text: dt.getData('text/plain'), json: dt.getData('application/x-milestone-tasks'), prevented: e.defaultPrevented }; }")
    clip_cut = lambda: ev("() => { const dt = new DataTransfer(); const e = new ClipboardEvent('cut', { clipboardData: dt, bubbles: true, cancelable: true }); document.body.dispatchEvent(e); return { text: dt.getData('text/plain'), json: dt.getData('application/x-milestone-tasks'), prevented: e.defaultPrevented }; }")
    clip_paste = lambda text, js="": ev("([t, j]) => { const dt = new DataTransfer(); dt.setData('text/plain', t); if (j) dt.setData('application/x-milestone-tasks', j); const e = new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true }); document.body.dispatchEvent(e); return e.defaultPrevented; }", [text, js])

    # ------------------------------------------------------------ selecting
    seed(FIVE)
    click("B")
    check("a click selects one task", sel() == ["B"] and ev("() => document.querySelectorAll('.grid-row.selected').length") == 1)
    click("D", ["Meta"])
    check("Ctrl+click adds a task to the selection (B and D), both rows are highlighted", sel() == ["B", "D"] and ev("() => document.querySelectorAll('.grid-row.selected').length") == 2, sel())
    check("...the chip in the toolbar says '2 selected'", "2 selected" in pg.inner_text("#selChip") and not ev("() => document.getElementById('selActions').classList.contains('hidden')"))
    click("B", ["Meta"])
    check("Ctrl+click on a selected task removes it (only D is left: the chip says '1 selected')", sel() == ["D"] and "1 selected" in pg.inner_text("#selChip"), sel())
    click("A"); click("D", ["Shift"])
    check("Shift+click selects the rows from the last clicked one (A to D)", sel() == ["A", "B", "C", "D"], sel())
    click("E", ["Shift"])
    check("...and Shift+click again extends from the same starting row (A to E)", sel() == ["A", "B", "C", "D", "E"], sel())
    click("C", ["Shift"])
    check("...or shrinks the range back (A to C)", sel() == ["A", "B", "C"], sel())
    click("E")
    check("a plain click goes back to one task", sel() == ["E"])
    click("A"); click("C", ["Meta"]); pg.click("#selChip"); pg.wait_for_timeout(80)
    check("clicking the chip clears the selection and the selection buttons disappear", sel() == [] and ev("() => document.getElementById('selActions').classList.contains('hidden')"))
    click("A"); click("C", ["Meta"]); pg.keyboard.press("Escape"); pg.wait_for_timeout(80)
    check("Escape clears a multi-selection", sel() == [])
    pg.locator("#gridRows").click(position={"x": 5, "y": 5}) if False else None
    ev("() => { document.activeElement && document.activeElement.blur(); }")
    pg.keyboard.press("Control+a"); pg.wait_for_timeout(80)
    check("Ctrl+A selects every visible task", sel() == ["A", "B", "C", "D", "E"], sel())
    pg.keyboard.press("Escape")
    seed([{"name": "G"}, {"name": "G1", "parent": "G"}, {"name": "G2", "parent": "G"}, {"name": "H"}])
    ev("() => { tasks.find(t => t.name === 'G').collapsed = true; render(); }")
    click("G"); click("H", ["Shift"])
    check("a range over a collapsed group covers the visible rows only (G and H; the hidden sub-tasks are not picked)", sel() == ["G", "H"], sel())
    pg.keyboard.press("Control+a")
    check("Ctrl+A with a collapsed group selects what is visible", sel() == ["G", "H"], sel())
    ev("() => { selectedTaskId = tasks.find(t => t.name === 'G').id; render(); }")
    check("assigning selectedTaskId directly (older code, tests) is a single selection", sel() == ["G"], sel())
    ev("() => { setSelection([tasks[0].id, tasks[3].id]); deleteTaskFlow(tasks[3].id); confirmModalAction(); }")
    check("a task that disappears leaves the selection without breaking anything", "H" not in sel(), sel())

    # ------------------------------------------------------------ buttons follow the selection
    seed(FIVE)
    check("nothing selected: Indent and Outdent are disabled and Edit / Duplicate / Copy / Delete are not shown at all", ev("() => document.getElementById('indentBtn').disabled && document.getElementById('outdentBtn').disabled") and ev("() => document.getElementById('selActions').classList.contains('hidden')") and not pg.locator("#bulkEditBtn").is_visible())
    click("B"); click("C", ["Meta"])
    check("with a selection they appear (with text labels) and are enabled", ev("() => ['indentBtn', 'cloneTaskBtn', 'copyBtn', 'bulkEditBtn', 'deleteTaskBtn'].every(i => !document.getElementById(i).disabled)") and all(pg.locator("#" + i).is_visible() for i in ["bulkEditBtn", "cloneTaskBtn", "copyBtn", "deleteTaskBtn"]) and [pg.inner_text("#" + i).strip() for i in ["bulkEditBtn", "cloneTaskBtn", "copyBtn", "deleteTaskBtn"]] == ["Edit", "Duplicate", "Copy", "Delete"])
    check("...the Edit button's tooltip names the count", "2 selected" in ev("() => document.getElementById('bulkEditBtn').title") or "all 2" in ev("() => document.getElementById('bulkEditBtn').title"), ev("() => document.getElementById('bulkEditBtn').title"))

    # ------------------------------------------------------------ delete, clone, indent, outdent on several
    seed([{"name": "G"}, {"name": "G1", "parent": "G"}, {"name": "G2", "parent": "G"}, {"name": "X"}, {"name": "Y"}, {"name": "Z"}])
    click("G"); click("G1", ["Meta"]); click("Y", ["Meta"])
    pg.keyboard.press("Delete"); pg.wait_for_selector("#confirmModalBg.open"); pg.wait_for_timeout(200)
    body = pg.inner_text("#confirmModalBg .modal-body") if pg.locator("#confirmModalBg .modal-body").count() else pg.inner_text("#confirmModalBg")
    check("the Delete key asks first; a parent and its child both selected count once: 2 tasks and 2 sub-tasks", "Delete these 2 tasks and 2 sub-tasks" in body, body)
    pg.click("#confirmModalBg .btn-danger"); pg.wait_for_timeout(200)
    check("...confirming deletes them (G with G1 and G2, and Y); X and Z stay", names() == ["X", "Z"] and sel() == [], names())
    check("...it is one Undo step (Ctrl+Z brings all four back)", (pg.keyboard.press("Control+z"), pg.wait_for_timeout(150), sorted(ev("() => tasks.map(t => t.name)")))[2] == ["G", "G1", "G2", "X", "Y", "Z"], ev("() => tasks.map(t => t.name)"))
    seed(FIVE)
    click("B"); click("D", ["Meta"]); pg.click("#cloneTaskBtn"); pg.wait_for_timeout(150)
    check("Clone with two selected clones both, each right below its original", names() == ["A", "B", "B (copy)", "C", "D", "D (copy)", "E"], names())
    check("...the copies are the selection and the toast says two tasks", sel() == ["B (copy)", "D (copy)"] and "Cloned 2 tasks" in pg.inner_text("#toastMsg"), (sel(), pg.inner_text("#toastMsg")))
    pg.click("#toastUndoBtn"); pg.wait_for_timeout(150)
    check("...and its Undo removes both", names() == ["A", "B", "C", "D", "E"] and sel() == ["B", "D"], (names(), sel()))
    seed(FIVE)
    click("C"); click("D", ["Shift"]); pg.click("#indentBtn"); pg.wait_for_timeout(100)
    check("Indent with C and D selected moves both under B (the task above the block)", names() == ["A", "B", "E"] and names(tid("B")) == ["C", "D"], (names(), names(tid("B"))))
    click("C"); click("D", ["Meta"]); pg.click("#outdentBtn"); pg.wait_for_timeout(100)
    check("Outdent brings them back out", names(tid("B")) == [] and sorted(names()) == ["A", "B", "C", "D", "E"], (names(), names(tid("B"))))
    seed([{"name": "P"}, {"name": "Q", "parent": "P"}, {"name": "R", "parent": "Q"}, {"name": "S"}])
    click("Q"); click("R", ["Meta"]); pg.click("#outdentBtn"); pg.wait_for_timeout(100)
    check("Outdent with a group and its own child selected moves the group; the child goes with it (not flattened)", names(tid("Q")) == ["R"] and "Q" in names(), (names(), names(tid("Q"))))

    # ------------------------------------------------------------ bulk edit
    seed([{"name": "G"}, {"name": "G1", "parent": "G", "s": "2026-09-07", "e": "2026-09-08"}, {"name": "G2", "parent": "G", "s": "2026-09-09", "e": "2026-09-10"},
          {"name": "X", "s": "2026-09-07", "e": "2026-09-11"}, {"name": "Y", "s": "2026-09-14", "e": "2026-09-15", "preds": [["X", "FS", 0]]}, {"name": "Z", "s": "2026-09-16", "e": "2026-09-17"}])
    click("X"); click("Y", ["Meta"]); click("G", ["Meta"]); pg.click("#bulkEditBtn"); pg.wait_for_selector("#bulkModalBg.open"); pg.wait_for_timeout(150)
    check("the Edit dialog opens with the count in its title and a hint about groups", pg.inner_text("#bulkTitle") == "Edit 3 tasks" and "Groups keep" in pg.inner_text("#bulkHint"), (pg.inner_text("#bulkTitle"), pg.inner_text("#bulkHint")))
    pg.click("#bulkModalBg .modal-footer .btn-primary")
    check("Apply with nothing ticked asks for a field", "Tick at least one" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    pg.fill("#bulkVal-progress", "60")
    check("typing in a field ticks its box", pg.is_checked("#bulkOn-progress"))
    pg.fill("#bulkVal-resource", "Anna"); pg.select_option("#bulkVal-color", "green")
    pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(200)
    get = lambda n, k: ev("([n, k]) => tasks.find(t => t.name === n)[k]", [n, k])
    check("% complete, resource and colour are set on the leaf tasks X and Y", get("X", "progress") == 60 and get("Y", "progress") == 60 and get("X", "resource") == "Anna" and get("Y", "color") == "green")
    check("...the group G keeps its computed progress but takes the resource and colour", ev("() => effectiveDates(tasks.find(t => t.name === 'G').id).progress") == 0 and get("G", "resource") == "Anna", get("G", "resource"))
    check("...the toast counts the tasks and mentions the group", "Updated 3 tasks" in pg.inner_text("#toastMsg") and "group" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    check("...unticked fields did not change (Z untouched, X's dates the same)", get("Z", "progress") == 0 and get("Z", "resource") == "" and dates("X") == ["2026-09-07", "2026-09-11"])
    pg.keyboard.press("Control+z"); pg.wait_for_timeout(120)
    check("Ctrl+Z undoes the whole bulk edit in one step", get("X", "progress") == 0 and get("Y", "resource") == "" and get("G", "color") is None)
    # shift dates
    click("X"); click("Z", ["Meta"]); pg.click("#bulkEditBtn"); pg.wait_for_selector("#bulkModalBg.open"); pg.wait_for_timeout(120)
    pg.fill("#bulkVal-shift", "3"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(200)
    check("Move dates by 3 working days: X 07.-11.09. becomes 10.-16.09., Z 16.-17.09. becomes 21.-22.09.", dates("X") == ["2026-09-10", "2026-09-16"] and dates("Z") == ["2026-09-21", "2026-09-22"], (dates("X"), dates("Z")))
    check("...Y, which follows X (Finish-to-Start), is pushed on by the schedule", dates("Y")[0] == "2026-09-17", dates("Y"))
    check("...X moved later than nothing constrains it: no pin (it has no links), Y is not pinned either", get("X", "constraintType") == "ASAP" and get("Y", "constraintType") == "ASAP")
    pg.keyboard.press("Control+z")
    click("Y"); ev("() => openBulkModal()"); pg.wait_for_selector("#bulkModalBg.open"); pg.wait_for_timeout(120)
    pg.fill("#bulkVal-shift", "2"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(200)
    check("moving a task LATER than its link needs is a deliberate delay: Y gets Start No Earlier Than (14.09. + 2 = 16.09.)", dates("Y")[0] == "2026-09-16" and get("Y", "constraintType") == "SNET" and get("Y", "constraintDate") == "2026-09-16", (dates("Y"), get("Y", "constraintType")))
    pg.keyboard.press("Control+z")
    ev("() => { tasks.find(t => t.name === 'Z').actualStart = '2026-09-16'; tasks.find(t => t.name === 'Z').startText = null; save(); render(); }")
    click("Z"); click("X", ["Meta"]); pg.click("#bulkEditBtn"); pg.wait_for_selector("#bulkModalBg.open"); pg.wait_for_timeout(120)
    pg.fill("#bulkVal-shift", "1"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(200)
    check("a task that has started is not moved; the toast says so", dates("Z")[0] == "2026-09-16" and "not moved" in pg.inner_text("#toastMsg") and dates("X")[0] == "2026-09-08", (dates("Z"), pg.inner_text("#toastMsg")))
    pg.keyboard.press("Control+z")
    # predecessor
    seed([{"name": "A", "s": "2026-09-07", "e": "2026-09-08"}, {"name": "B", "s": "2026-09-07", "e": "2026-09-08"}, {"name": "C", "s": "2026-09-07", "e": "2026-09-08"}, {"name": "G"}, {"name": "G1", "parent": "G"}])
    click("B"); click("C", ["Meta"]); click("A", ["Meta"]); pg.click("#bulkEditBtn"); pg.wait_for_selector("#bulkModalBg.open"); pg.wait_for_timeout(120)
    pg.fill("#bulkVal-predId", "1"); pg.select_option("#bulkVal-predType", "SS"); pg.fill("#bulkVal-predLag", "1"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(200)
    pl = lambda n: ev("n => tasks.find(t => t.name === n).predecessors.map(p => [byId(p.id).name, p.type, p.lag])", n)
    check("Add predecessor #1 (A) as Start-to-Start +1 to B and C; A itself is skipped (no self-link)", pl("B") == [["A", "SS", 1]] and pl("C") == [["A", "SS", 1]] and pl("A") == [], (pl("A"), pl("B"), pl("C")))
    check("...and the tasks are placed by the new link (B, C start the working day after A: 08.09.)", dates("B")[0] == "2026-09-08" and dates("C")[0] == "2026-09-08", (dates("B"), dates("C")))
    check("...the toast says one was not linked", "not linked" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    click("C"); ev("() => openBulkModal()"); pg.wait_for_selector("#bulkModalBg.open"); pg.fill("#bulkVal-predId", "2"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(200)
    click("B"); ev("() => openBulkModal()"); pg.wait_for_selector("#bulkModalBg.open"); pg.fill("#bulkVal-predId", "3"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(200)
    check("a link that would close a cycle (C after B, then B after C) is skipped", pl("B") == [["A", "SS", 1]] and "not linked" in pg.inner_text("#toastMsg"), (pl("B"), pg.inner_text("#toastMsg")))
    click("A"); ev("() => openBulkModal()"); pg.wait_for_selector("#bulkModalBg.open"); pg.fill("#bulkVal-predId", "99"); pg.click("#bulkModalBg .modal-footer .btn-primary")
    check("a task number that does not exist is refused", "No task #99" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    pg.fill("#bulkVal-predId", "4"); pg.click("#bulkModalBg .modal-footer .btn-primary")
    check("...and so is a summary task as a predecessor", "summary" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    pg.fill("#bulkVal-predId", ""); pg.uncheck("#bulkOn-pred"); pg.fill("#bulkVal-progress", "150"); pg.click("#bulkModalBg .modal-footer .btn-primary")
    check("a % complete outside 0-100 is refused", "between 0 and 100" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    pg.fill("#bulkVal-progress", ""); pg.uncheck("#bulkOn-progress"); pg.select_option("#bulkVal-mode", "manual"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(150)
    check("Task Mode can be set for the selection (A becomes Manually Scheduled)", get("A", "taskMode") == "manual")
    # custom fields
    ev("() => { project.fieldNames = { text1: 'Cost centre', number1: 'Budget', flag1: 'Approved' }; normalizeData(); colHidden.delete('text1'); colHidden.delete('number1'); colHidden.delete('flag1'); render(); }")
    click("A"); click("B", ["Meta"]); pg.click("#bulkEditBtn"); pg.wait_for_selector("#bulkModalBg.open"); pg.wait_for_timeout(120)
    check("custom fields that are shown as columns are offered (Text1, Number1, Flag1)", all(pg.locator(f"#bulkOn-{c}").count() == 1 for c in ("text1", "number1", "flag1")) and pg.locator("#bulkOn-text2").count() == 0)
    pg.fill("#bulkVal-text1", "Cost centre 7"); pg.fill("#bulkVal-number1", "12,5"); pg.select_option("#bulkVal-flag1", "1"); pg.click("#bulkModalBg .modal-footer .btn-primary"); pg.wait_for_timeout(150)
    cf = lambda n: ev("n => tasks.find(t => t.name === n).custom", n)
    check("...text, number (12,5 -> 12.5) and flag values are set on both", cf("A") == {"text1": "Cost centre 7", "number1": 12.5, "flag1": True} and cf("B") == cf("A"), (cf("A"), cf("B")))
    click("A"); ev("() => openBulkModal()"); pg.wait_for_selector("#bulkModalBg.open"); pg.fill("#bulkVal-number1", "abc"); pg.click("#bulkModalBg .modal-footer .btn-primary")
    check("a number that is not a number is refused", "isn't a number" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    pg.keyboard.press("Escape"); pg.wait_for_timeout(200)
    check("Escape closes the dialog", not ev("() => document.getElementById('bulkModalBg').classList.contains('open')"))
    click("A"); ev("() => openBulkModal()"); pg.wait_for_selector("#bulkModalBg.open"); pg.wait_for_timeout(100)
    check("a single selected task can be edited the same way (title 'Edit task')", pg.inner_text("#bulkTitle") == "Edit task")
    pg.keyboard.press("Escape")
    # the toolbar's Edit button: one task -> the full task dialog (like a double-click), several -> the bulk dialog
    seed([{"name": "A", "s": "2026-09-07", "e": "2026-09-08"}, {"name": "B", "s": "2026-09-09", "e": "2026-09-10"}, {"name": "C", "s": "2026-09-11", "e": "2026-09-11"}])
    modal = lambda: ev("() => [document.getElementById('taskModalBg').classList.contains('open'), document.getElementById('bulkModalBg').classList.contains('open')]")
    click("B"); pg.click("#bulkEditBtn"); pg.wait_for_timeout(300)
    check("Edit button with ONE task selected opens the full task dialog for it, not the bulk dialog", modal() == [True, False] and pg.input_value("#taskNameInput") == "B", (modal(), pg.input_value("#taskNameInput")))
    check("...it is the very dialog a double-click opens (Task Mode, dates, duration, constraint fields are there)", all(pg.locator(sel_).count() == 1 for sel_ in ["#taskModeInput", "#taskStartInput", "#taskDurationInput"]))
    pg.keyboard.press("Escape"); pg.wait_for_timeout(250)
    click("A"); click("C", ["Meta"]); pg.click("#bulkEditBtn"); pg.wait_for_timeout(300)
    check("...with TWO selected it opens the bulk dialog ('Edit 2 tasks')", modal() == [False, True] and pg.inner_text("#bulkTitle") == "Edit 2 tasks", (modal(), pg.inner_text("#bulkTitle")))
    pg.keyboard.press("Escape"); pg.wait_for_timeout(250)
    click("B"); tip1 = ev("() => document.getElementById('bulkEditBtn').title"); click("A"); click("B", ["Meta"]); tip2 = ev("() => document.getElementById('bulkEditBtn').title")
    check("...tooltip: 'Edit the selected task' for one, 'Change a field for all 2 selected tasks' for two", "Edit the selected task" in tip1 and "all 2 selected" in tip2, (tip1, tip2))

    # ------------------------------------------------------------ copy and paste
    seed([{"name": "Plan", "extra": {"color": "teal"}}, {"name": "Step 1", "parent": "Plan", "s": "2026-09-07", "e": "2026-09-08", "extra": {"resource": "Anna", "progress": 30}}, {"name": "Step 2", "parent": "Plan", "s": "2026-09-09", "e": "2026-09-11", "preds": [["Step 1", "FS", 1]]},
          {"name": "Other", "s": "2026-09-14", "e": "2026-09-15", "preds": [["Step 2", "FS", 0]]}, {"name": "Last", "s": "2026-09-16", "e": "2026-09-17"}])
    click("Plan")
    cp = clip_copy()
    check("Copy is handled (the browser's default is prevented) and puts a table on the clipboard", cp["prevented"] and cp["text"].startswith("ID\t"), cp["text"][:80])
    lines = cp["text"].split("\n"); head = lines[0].split("\t")
    check("...header row: ID, then the visible columns with their names (Task Name, Start, Finish …)", head[0] == "ID" and "Task Name" in head and "Start" in head and "Finish" in head and "Duration" in head, head)
    ni = head.index("Task Name")
    check("...one line per task including the sub-tasks, names indented by outline level", len(lines) == 4 and lines[1].split("\t")[ni] == "Plan" and lines[2].split("\t")[ni] == "  Step 1" and lines[3].split("\t")[ni] == "  Step 2", [l.split("\t")[ni] for l in lines])
    check("...dates are dd.mm.yyyy, % is shown, the link is written as MS Project writes it (1FS+1)", "07.09.2026" in lines[2] and "30%" in lines[2] and "2FS+1" in lines[3].replace("\t", " ") or "1FS+1" in lines[3], lines[3])
    check("...and the private task format is on the clipboard too", '"app":"milestone"' in cp["json"].replace(" ", "") and len(__import__("json").loads(cp["json"])["tasks"]) == 3)
    click("Last")
    check("Paste (with the private format) inserts copies below the selected task: Plan (copy of the group with its 2 sub-tasks) after Last", clip_paste(cp["text"], cp["json"]) and names() == ["Plan", "Other", "Last", "Plan"] and len(ev("() => tasks")) == 8, (names(), len(ev("() => tasks"))))
    newplan = ev("() => childrenOf(null)[3].id")
    check("...the pasted group has its two sub-tasks, colour and resource kept, links between the copies point at the copies", ev("(id) => { const k = childrenOf(id); return k.map(t => t.name).join() === 'Step 1,Step 2' && byId(id).color === 'teal' && k[0].resource === 'Anna' && k[1].predecessors.length === 1 && k[1].predecessors[0].id === k[0].id && k[1].predecessors[0].lag === 1; }", newplan))
    check("...with new ids, and the pasted top task is the selection", ev("(id) => new Set(tasks.map(t => t.id)).size === tasks.length && selectedTaskId === id", newplan))
    check("...the toast says 3 tasks and Ctrl+Z", "Pasted 3 tasks" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    check("the original tasks and their links are untouched by the paste", ev("() => { const o = tasks.find(t => t.name === 'Other'); return o.predecessors.length === 1 && byId(o.predecessors[0].id).name === 'Step 2' && childrenOf(tasks.find(t => t.name === 'Plan').id).length === 2; }"))
    pg.keyboard.press("Control+z"); pg.wait_for_timeout(150)
    check("Ctrl+Z undoes the paste in one step", len(ev("() => tasks")) == 5 and names() == ["Plan", "Other", "Last"], names())
    click("Step 2")
    cp2 = clip_copy()
    click("Last"); clip_paste(cp2["text"], cp2["json"])
    check("copying one sub-task and pasting it at the top level of another position: it lands below the selected task at THAT level (top level, after Last), keeping its link to the original Step 1", names() == ["Plan", "Other", "Last", "Step 2"] and ev("() => { const t = childrenOf(null)[3]; return t.predecessors.length === 1 && byId(t.predecessors[0].id).name === 'Step 1'; }"), names())
    pg.keyboard.press("Control+z")
    # no selection: to the end
    ev("() => setSelection([])"); render_ok = ev("() => render()")
    clip_paste("Alpha\nBeta", "")
    check("Paste with nothing selected appends at the end of the top level (plain names, one per line)", names()[-2:] == ["Alpha", "Beta"], names())
    pg.keyboard.press("Control+z")
    # the private clip is also found from the text alone (browsers may drop custom formats)
    click("Plan"); clip_copy(); click("Last")
    ev("() => { }")
    clip_paste(cp["text"], "")
    check("if only the text comes back (a browser dropped the private format), the remembered copy is used: everything is kept (colour teal)", names()[-1] == "Plan" and ev("() => childrenOf(null)[3].color") == "teal", names())
    pg.keyboard.press("Control+z")
    # cut
    click("Other"); cut = clip_cut(); pg.wait_for_timeout(150)
    check("Cut copies and removes the task (Other is gone, the toast says so, the table is on the clipboard)", cut["prevented"] and "Other" not in names() and "Cut 1 task" in pg.inner_text("#toastMsg") and "Other" in cut["text"], (names(), pg.inner_text("#toastMsg")))
    click("Plan"); clip_paste(cut["text"], cut["json"]); pg.wait_for_timeout(150)
    check("...pasting puts it back below the selected task (a new task: Other after Plan)", names() == ["Plan", "Other", "Last"], names())
    pg.keyboard.press("Control+z")
    pg.keyboard.press("Control+z"); pg.wait_for_timeout(150)
    check("...and Ctrl+Z twice puts everything back as it was (paste undone, then the cut)", names() == ["Plan", "Other", "Last"], names())

    # ------------------------------------------------------------ pasting rows from Excel
    seed([{"name": "Existing"}])
    click("Existing")
    xl = "Task Name\tStart\tFinish\tDuration\t% Complete\tResource\nPhase 1\t07.09.2026\t18.09.2026\t\t\t\n  Design\t07.09.2026\t11.09.2026\t5 days\t50%\tAnna\n  Build\t14.09.2026\t\t5 days\t0%\tBen\nPhase 2\tTBD\t\t\t\t\n"
    clip_paste(xl, "")
    check("rows pasted from Excel become tasks below the selected one: header names are recognised, indentation gives the outline", names() == ["Existing", "Phase 1", "Phase 2"] and names(tid("Phase 1")) == ["Design", "Build"], (names(), names(tid("Phase 1"))))
    check("...dates, duration, %, resource are read; a start and a duration give the finish (Build 14.-18.09.)", dates("Design") == ["2026-09-07", "2026-09-11"] and dates("Build") == ["2026-09-14", "2026-09-18"] and get("Design", "progress") == 50 and get("Design", "resource") == "Anna")
    check("...a task with TBD dates comes in Manually Scheduled with the text kept", get("Phase 2", "taskMode") == "manual" and get("Phase 2", "startText") == "TBD")
    check("...the toast says rows were pasted as tasks", "Pasted 4 rows" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    pg.keyboard.press("Control+z")
    check("and it is one Undo step", names() == ["Existing"], names())
    ev("() => setSelection([])")
    clip_paste("ID\tTask Name\tStart\tFinish\tPredecessors\n1\tFirst\t07.09.2026\t08.09.2026\t\n2\tSecond\t09.09.2026\t10.09.2026\t1FS\n3\tThird\t11.09.2026\t11.09.2026\t2SS+1\n", "")
    check("links in pasted rows follow the ID column of the pasted block", ev("() => { const s = tasks.find(t => t.name === 'Second'), f = tasks.find(t => t.name === 'First'), th = tasks.find(t => t.name === 'Third'); return s.predecessors[0].id === f.id && th.predecessors[0].id === s.id && th.predecessors[0].type === 'SS' && th.predecessors[0].lag === 1; }"))
    pg.keyboard.press("Control+z")
    # typing in a field is left alone
    click("Existing")
    ev("() => { startInlineEdit(tasks[0].id, 'name'); }"); pg.wait_for_timeout(200)
    before = len(ev("() => tasks"))
    handled = ev("() => { const dt = new DataTransfer(); dt.setData('text/plain', 'Should not become a task'); const inp = document.querySelector('#gridRows input.inline-edit, #gridRows input'); const e = new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true }); (inp || document.body).dispatchEvent(e); return e.defaultPrevented; }")
    check("pasting while typing in a cell is the browser's own: nothing becomes a task", not handled and len(ev("() => tasks")) == before, handled)
    pg.keyboard.press("Escape")
    ev("() => setSelection([])")
    check("pasting an empty clipboard does nothing", (clip_paste("   ", ""), len(ev("() => tasks")))[1] == before)
    check("the Copy button and the Add menu's Paste work (Copy remembers the selection, Paste puts it back below the selected task)", (click("Existing"), pg.click("#copyBtn"), pg.wait_for_timeout(100), pg.click("#addMenuBtn"), pg.click("#pasteBtn"), pg.wait_for_timeout(300), names().count("Existing"))[6] == 2, names())
    # the dialog looks like the others: rounded, padded, bordered fields, and the whole predecessor row fits its width
    ev("() => { setSelection(tasks.slice(0, 2).map(t => t.id)); render(); openBulkModal(); }"); pg.wait_for_timeout(300)
    look = ev("""() => [...document.querySelectorAll('#bulkModalBg .bulk-ctl input, #bulkModalBg .bulk-ctl select')].filter(e => e.offsetParent).map(e => { const c = getComputedStyle(e); return [e.id, parseFloat(c.borderRadius), parseFloat(c.paddingLeft), parseFloat(c.borderTopWidth)]; })""")
    check("the bulk-edit fields are rounded (7px), padded (10px) and bordered like the other dialogs' fields, not the browser's plain boxes", len(look) >= 8 and all(r == 7 and p_ == 10 and w == 1 for _, r, p_, w in look), look)
    check("...the dialog is 520px wide and the link type shows in full ('FS' with a tooltip), none of the three predecessor fields is cut off", round(pg.locator("#bulkModalBg .modal").bounding_box()["width"]) == 520 and ev("() => ['bulkVal-predId', 'bulkVal-predType', 'bulkVal-predLag'].every(i => { const e = document.getElementById(i); return e.getBoundingClientRect().width >= 60; })") and ev("() => document.getElementById('bulkVal-predType').selectedOptions[0].textContent") == "FS")
    pg.keyboard.press("Escape"); pg.wait_for_timeout(200)
    check("no console errors", not errors, errors[:5])
    print("console errors/warnings:", errors[:5]); print(f"{sum(results)}/{len(results)} passed"); b.close()
