import json
import openpyxl
from playwright.sync_api import sync_playwright

import os
URL = os.environ.get("MILESTONE_URL", "http://127.0.0.1:8937/milestone.html")
errors, results = [], []
def check(name, cond, detail=""):
    results.append(bool(cond)); print(("PASS  " if cond else "FAIL  ") + name + (f"   [{str(detail)[:260]}]" if not cond and detail else ""))

KINDS = [("text", "Text"), ("number", "Number"), ("date", "Date"), ("flag", "Flag")]
IDS = [k + str(i) for k, _ in KINDS for i in range(1, 6)]
NAMES = [l + str(i) for k, l in KINDS for i in range(1, 6)]
DEFAULT_SHOWN = ["mode", "wbs", "name", "start", "end", "actualStart", "actualFinish", "duration", "progress", "preds", "status"]

MK = """(specs) => { tasks.length = 0; selectedTaskId = null; colFilters = newColFilters(); filterPinned.clear();
  let n = 0; const ids = {};
  for (const sp of specs) { const t = Object.assign({id: genId(), name: sp.name, parentId: sp.parent ? ids[sp.parent] : null, order: n++, startDate: sp.s || '2026-09-07', endDate: sp.e || sp.s || '2026-09-11', progress: sp.p || 0, milestone: false, color: null, predecessors: [], collapsed: false, updatedAt: 1, constraintType: 'ASAP', constraintDate: null, taskMode: 'auto', resource: '', actualStart: null, actualFinish: null}, sp.extra || {}); tasks.push(t); ids[sp.name] = t.id; }
  currentView = 'tasks'; save(); render(); }"""

with sync_playwright() as p:
    b = p.chromium.launch(headless=True)
    ctx = b.new_context(viewport={"width": 1600, "height": 900}, accept_downloads=True); ctx.add_init_script("delete window.showOpenFilePicker; delete window.showSaveFilePicker")
    pg = ctx.new_page(); pg.on("pageerror", lambda e: errors.append(str(e))); pg.on("console", lambda m: errors.append(m.text) if m.type in ("error", "warning") else None)
    pg.goto(URL); pg.wait_for_selector("#addTaskBtn"); pg.evaluate("() => localStorage.clear()"); pg.reload(); pg.wait_for_selector("#addTaskBtn")
    make = lambda specs: (pg.evaluate(MK, specs), pg.wait_for_timeout(100))
    head_cols = lambda: pg.evaluate("() => [...document.querySelectorAll('#gridHeader .col-filter-btn')].map(b => b.dataset.col)")
    head_text = lambda col: pg.locator(f"#gridHeader .col-head:has(.col-filter-btn[data-col='{col}']) > span").text_content().strip()
    names = lambda: pg.evaluate("() => visibleTaskList().map(x => x.task.name)")
    tid = lambda n: pg.evaluate("n => tasks.find(t => t.name === n).id", n)
    custom = lambda n: pg.evaluate("n => { const t = tasks.find(x => x.name === n); return t.custom === undefined ? 'NONE' : t.custom; }", n)
    show = lambda *cols: (pg.evaluate("cs => { cs.forEach(c => colHidden.delete(c)); save(); render(); }", list(cols)), pg.wait_for_timeout(80))
    def cell(name, col):
        i = head_cols().index(col)
        return pg.locator(f".grid-row[data-id='{tid(name)}']").locator(":scope > div").nth(1 + i)
    def wait_focus(): pg.wait_for_function("() => document.activeElement && document.activeElement.classList.contains('inline-edit')")
    def edit(name, col, value):
        cell(name, col).click(); pg.wait_for_selector(".inline-edit"); wait_focus()
        pg.fill(".inline-edit", value); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    def open_cols():
        if not pg.locator("#columnsMenu.open").count(): pg.click("#columnsBtn")
        pg.wait_for_selector("#columnsMenu.open")
    def close_cols(): pg.keyboard.press("Escape"); pg.wait_for_timeout(80)
    def open_dialog(n): pg.evaluate("n => openTaskModal(tasks.find(t => t.name === n).id)", n); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(80)
    def close_dialog(): pg.evaluate("() => closeTaskModal()"); pg.wait_for_timeout(50)
    def rename_via_menu(col, new):
        open_cols(); pg.click(f"#columnsMenu .cols-row:has(input[data-col='{col}']) .cols-rename"); pg.wait_for_selector("#fieldNameModalBg.open")
        pg.fill("#fieldNameInput", new); pg.keyboard.press("Enter"); pg.wait_for_timeout(120)

    # ================================================================= the 20 fields and the Columns menu
    make([{"name": "One"}, {"name": "Two", "s": "2026-09-14", "e": "2026-09-18"}])
    check("out of the box none of the custom fields is shown", head_cols() == DEFAULT_SHOWN, head_cols())
    open_cols()
    listed = pg.evaluate("() => [...document.querySelectorAll('#columnsMenu input[data-col]')].map(i => [i.dataset.col, i.closest('label').innerText.trim(), i.checked])")
    custom_rows = [x for x in listed if x[0] in IDS]
    check("the Columns menu lists all 20: Text1-5, Number1-5, Date1-5, Flag1-5, with those names", [x[0] for x in custom_rows] == IDS and [x[1] for x in custom_rows] == NAMES, custom_rows[:3])
    check("...all unticked", not any(x[2] for x in custom_rows))
    check("...each has a rename pencil (the standard columns don't)", pg.locator("#columnsMenu .cols-rename").count() == 20 and pg.locator("#columnsMenu .cols-row:has(input[data-col='start']) .cols-rename").count() == 0)
    geo = pg.evaluate("() => { const m = document.getElementById('columnsMenu'), r = m.getBoundingClientRect(); return {scrolls: m.scrollHeight > m.clientHeight, bottom: r.bottom, vh: innerHeight}; }")
    check("with 33 rows the menu scrolls and stays inside the window", geo["scrolls"] and geo["bottom"] <= geo["vh"], geo)
    mx = pg.evaluate("() => { const m = document.getElementById('columnsMenu'); m.scrollTop = m.scrollHeight; return m.scrollTop; }")
    pg.locator("#columnsMenu input[data-col='number1']").set_checked(True); pg.wait_for_timeout(100)
    check("ticking a row doesn't throw the menu's scroll position back to the top (scrolled to the bottom, it stays there)", mx > 50 and abs(pg.evaluate("() => document.getElementById('columnsMenu').scrollTop") - mx) <= 2, (mx, pg.evaluate("() => document.getElementById('columnsMenu').scrollTop")))
    check("ticking Number1 shows a column headed 'Number1' with its filter funnel", head_cols() == DEFAULT_SHOWN + ["number1"] and head_text("number1") == "Number1", head_cols())
    pg.locator("#columnsMenu input[data-col='number1']").set_checked(False); close_cols()
    show("text1", "number1", "date1", "flag1")
    check("the four kinds sit after Resource in their default order", head_cols()[-4:] == ["text1", "number1", "date1", "flag1"], head_cols())
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(150)
    check("the chosen custom columns are remembered across a reload (device preference)", head_cols()[-4:] == ["text1", "number1", "date1", "flag1"])
    pg.evaluate("() => { const p = JSON.parse(localStorage.getItem('milestone-prefs')); p.cols.order = p.cols.order.filter(c => !/^(text|number|date|flag)\\d$/.test(c)); p.cols.hidden = p.cols.hidden.filter(c => !/^(text|number|date|flag)\\d$/.test(c)); localStorage.setItem('milestone-prefs', JSON.stringify(p)); }")
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(150)
    check("prefs saved before custom fields existed: they arrive appended and hidden", head_cols() == DEFAULT_SHOWN and pg.evaluate("() => colOrder.slice(-20)") == IDS, head_cols())
    show("text1", "number1", "date1", "flag1")

    # ================================================================= editing in the list
    edit("One", "text1", "  Hello world  ")
    check("Text: click, type, Enter -> saved (trimmed) on the task", custom("One") == {"text1": "Hello world"} and cell("One", "text1").inner_text().strip() == "Hello world", custom("One"))
    check("...the change is stamped so it syncs", pg.evaluate("() => tasks.find(t => t.name === 'One').updatedAt > 1"))
    cell("One", "text1").click(); wait_focus(); pg.fill(".inline-edit", "NOPE"); pg.keyboard.press("Escape"); pg.wait_for_timeout(80)
    check("Escape cancels a text edit", custom("One") == {"text1": "Hello world"})
    check("the text editor allows up to 255 characters", (cell("One", "text1").click() or True) and pg.get_attribute(".inline-edit", "maxlength") == "255"); pg.keyboard.press("Escape")
    edit("One", "text1", "<b>bold?</b> & \"quotes\"")
    check("text is shown literally, never as markup", cell("One", "text1").inner_text().strip() == '<b>bold?</b> & "quotes"' and pg.locator(".grid-row b").count() == 0)
    edit("One", "number1", "12,5")
    check("Number: a comma decimal is accepted (12,5 -> 12.5) and shown", custom("One")["number1"] == 12.5 and cell("One", "number1").inner_text().strip() == "12.5", custom("One"))
    edit("One", "number1", "abc")
    check("...text in a number field is refused (toast, nothing changes)", custom("One")["number1"] == 12.5 and "isn't a number" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    edit("One", "number1", "-3")
    check("...negative numbers and zero work", custom("One")["number1"] == -3)
    edit("One", "number1", "0")
    check("...0 is a value (not empty)", custom("One")["number1"] == 0 and cell("One", "number1").inner_text().strip() == "0")
    cell("One", "date1").click(); pg.wait_for_selector(".inline-edit"); wait_focus()
    check("Date: opens a native date editor", pg.get_attribute(".inline-edit", "type") == "date")
    pg.fill(".inline-edit", "2026-12-24"); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    check("...saved as an ISO date and shown dd.mm.yyyy", custom("One")["date1"] == "2026-12-24" and cell("One", "date1").inner_text().strip() == "24.12.2026")
    cell("One", "flag1").click(); pg.wait_for_timeout(80)
    check("Flag: one click sets it (a tick appears), stored as true", custom("One")["flag1"] is True and cell("One", "flag1").locator("i.fa-check").count() == 1 and pg.locator(".inline-edit").count() == 0)
    cell("One", "flag1").click(); pg.wait_for_timeout(80)
    check("...another click clears it", "flag1" not in custom("One") and cell("One", "flag1").locator("i").count() == 0)
    # clearing everything removes the object
    cell("One", "flag1").click(); pg.wait_for_timeout(60)
    for col, val in (("text1", ""), ("number1", ""), ("date1", "")): edit("One", col, val)
    cell("One", "flag1").click(); pg.wait_for_timeout(60)
    check("clearing every value removes the task's custom object altogether (no empty leftovers)", custom("One") == "NONE", custom("One"))
    # groups and milestones
    make([{"name": "Grp"}, {"name": "Kid", "parent": "Grp"}, {"name": "MS", "extra": {"milestone": True}}])
    show("text1", "flag1")
    edit("Grp", "text1", "group note"); cell("MS", "flag1").click(); pg.wait_for_timeout(60); edit("MS", "text1", "milestone note")
    check("groups and milestones can have custom values too (nothing is rolled up)", custom("Grp") == {"text1": "group note"} and custom("MS") == {"flag1": True, "text1": "milestone note"} and custom("Kid") == "NONE", (custom("Grp"), custom("MS"), custom("Kid")))
    check("a new task has no custom object", pg.evaluate("() => { addTask(); const t = tasks[tasks.length - 1]; const r = !('custom' in t); closeTaskModal(); return r; }"))

    # ================================================================= the dialog: a separate tab
    make([{"name": "Alpha", "extra": {"custom": {"text2": "hello", "number3": 7.25, "date4": "2026-10-01", "flag5": True}}}, {"name": "Beta"}])
    open_dialog("Alpha")
    check("dialog: two tabs, General (active) and Custom fields", pg.locator("#taskModalBg .modal-tab").all_inner_texts()[0].strip() == "General" and "Custom fields" in pg.locator("#taskModalBg .modal-tab").all_inner_texts()[1] and pg.locator("#taskTabBtnGeneral.active").count() == 1)
    check("...the General tab shows the usual fields; the custom ones aren't there", pg.locator("#taskTabGeneral").is_visible() and not pg.locator("#taskTabCustom").is_visible() and pg.locator("#taskNameInput").is_visible())
    check("...the tab shows how many custom values the task has (4)", pg.inner_text("#taskCustomBadge").strip() == "4", pg.inner_text("#taskCustomBadge"))
    pg.click("#taskTabBtnCustom")
    check("Custom fields tab: shown, General hidden", pg.locator("#taskTabCustom").is_visible() and not pg.locator("#taskTabGeneral").is_visible() and pg.locator("#taskTabBtnCustom.active").count() == 1)
    secs = pg.evaluate("() => [...document.querySelectorAll('#taskCustomFields .cf-section')].map(s => [s.querySelector('.cf-title').innerText.trim(), s.querySelectorAll('input').length, s.querySelector('input').type])")
    check("...four sections of five fields: Text, Number, Date, Flag", secs == [["TEXT", 5, "text"], ["NUMBER", 5, "number"], ["DATE", 5, "date"], ["FLAG", 5, "checkbox"]] or [[a.upper(), n, t] for a, n, t in secs] == [["TEXT", 5, "text"], ["NUMBER", 5, "number"], ["DATE", 5, "date"], ["FLAG", 5, "checkbox"]], secs)
    check("...labelled with the default names", pg.evaluate("() => [...document.querySelectorAll('#taskCustomFields .cf-label > span:first-child, #taskCustomFields .cf-flag label span')].map(e => e.innerText.trim())") == NAMES)
    check("...the task's values are filled in", pg.input_value("#cf_text2") == "hello" and pg.input_value("#cf_number3") == "7.25" and pg.input_value("#cf_date4") == "2026-10-01" and pg.is_checked("#cf_flag5") and pg.input_value("#cf_text1") == "")
    pg.fill("#cf_text1", "first"); pg.fill("#cf_number1", "42"); pg.fill("#cf_date1", "2026-11-11"); pg.check("#cf_flag1"); pg.uncheck("#cf_flag5"); pg.fill("#cf_text2", "")
    check("the badge follows what is typed (4 -> 6: +4 new, -2 cleared)", pg.inner_text("#taskCustomBadge").strip() == "6", pg.inner_text("#taskCustomBadge"))
    pg.click("#taskTabBtnGeneral"); pg.fill("#taskNameInput", "Alpha renamed")
    pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(150)
    check("Save from any tab saves both: the General edit and the custom values", pg.evaluate("() => tasks.find(t => t.name === 'Alpha renamed') !== undefined") and pg.evaluate("() => tasks.find(t => t.name === 'Alpha renamed').custom") == {"text1": "first", "number1": 42, "date1": "2026-11-11", "flag1": True, "number3": 7.25, "date4": "2026-10-01"}, pg.evaluate("() => tasks[0].custom"))
    open_dialog("Alpha renamed")
    check("the dialog always opens on the General tab", pg.locator("#taskTabGeneral").is_visible() and not pg.locator("#taskTabCustom").is_visible())
    pg.click("#taskTabBtnCustom"); pg.fill("#cf_text3", "DISCARD"); close_dialog()
    check("Cancel discards custom edits", "text3" not in custom("Alpha renamed"))
    open_dialog("Beta"); pg.click("#taskTabBtnCustom")
    check("a task with no custom values: empty fields and no badge", pg.input_value("#cf_text1") == "" and pg.locator("#taskCustomBadge.hidden").count() == 1)
    pg.fill("#cf_text1", "   "); pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(120)
    check("whitespace-only text isn't a value", custom("Beta") == "NONE", custom("Beta"))
    open_dialog("Beta"); pg.click("#taskTabBtnGeneral"); pg.fill("#taskActualStartInput", "2026-09-20"); pg.fill("#taskActualFinishInput", "2026-09-10")
    pg.click("#taskTabBtnCustom"); pg.fill("#cf_text2", "x"); pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(150)
    check("a validation error on the General tab (Actual Finish before its start), hit when saving from the Custom tab, switches back to General and keeps the dialog open", pg.locator("#taskModalBg.open").count() == 1 and pg.locator("#taskTabGeneral").is_visible() and "before" in pg.inner_text("#toastMsg"), pg.inner_text("#toastMsg"))
    close_dialog()

    # ================================================================= renaming
    make([{"name": "R1", "extra": {"custom": {"text1": "a", "number1": 5, "date1": "2026-09-30", "flag1": True}}}, {"name": "R2", "extra": {"custom": {"text1": "b", "number1": 9}}}])
    show("text1", "number1", "date1", "flag1")
    open_cols(); pg.click("#columnsMenu .cols-row:has(input[data-col='text1']) .cols-rename"); pg.wait_for_selector("#fieldNameModalBg.open"); pg.wait_for_timeout(100)
    check("the pencil in the Columns menu opens a rename dialog with the current name selected", pg.input_value("#fieldNameInput") == "Text1" and "Default name: Text1" in pg.inner_text("#fieldNameHint") and pg.evaluate("() => document.activeElement.id") == "fieldNameInput")
    check("...'Use default name' is disabled while it has the default", pg.locator("#fieldNameResetBtn").is_disabled())
    pg.fill("#fieldNameInput", "Cost centre"); pg.keyboard.press("Enter"); pg.wait_for_timeout(120)
    check("renaming: the list header takes the new name", head_text("text1") == "Cost centre", head_text("text1"))
    check("...and so does the menu (which stays open), with its scroll and the pencil intact", pg.locator("#columnsMenu.open").count() == 1 and "Cost centre" in pg.locator("#columnsMenu .cols-row:has(input[data-col='text1'])").inner_text())
    close_cols()
    check("the name is stored on the plan (project.fieldNames), only for what changed", pg.evaluate("() => project.fieldNames") == {"text1": "Cost centre"} and pg.evaluate("() => JSON.parse(localStorage.getItem('milestone-plan-' + currentPlanId)).project.fieldNames") == {"text1": "Cost centre"})
    check("...not in the device preferences", "Cost centre" not in json.dumps(pg.evaluate("() => JSON.parse(localStorage.getItem('milestone-prefs'))")))
    check("...renaming stamps the plan so the change syncs", pg.evaluate("() => project.updatedAt > 5"))
    check("...and the exported/synced payload carries it", pg.evaluate("() => syncPayload().project.fieldNames.text1") == "Cost centre")
    check("the cell tooltip and the filter button use the new name", pg.locator(".col-filter-btn[data-col='text1']").get_attribute("title") == "Filter Cost centre")
    open_dialog("R1"); pg.click("#taskTabBtnCustom")
    check("the dialog's Custom tab shows the new name too", pg.evaluate("() => document.querySelector('#taskCustomFields .cf-label > span:first-child').innerText.trim()") == "Cost centre")
    # rename from the dialog, while typing
    pg.fill("#cf_text3", "typed but unsaved")
    pg.click("#taskCustomFields .field:has(#cf_number1) .cf-rename"); pg.wait_for_selector("#fieldNameModalBg.open")
    top = pg.evaluate("() => { const r = document.getElementById('fieldNameInput').getBoundingClientRect(); return document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2).id; }")
    check("the rename dialog opens above the task dialog", top == "fieldNameInput", top)
    pg.fill("#fieldNameInput", "Budget"); pg.keyboard.press("Enter"); pg.wait_for_timeout(150)
    check("renaming from the dialog works, the dialog stays open on the Custom tab, and unsaved typing survives", pg.locator("#taskModalBg.open").count() == 1 and pg.locator("#taskTabCustom").is_visible() and pg.input_value("#cf_text3") == "typed but unsaved" and head_text("number1") == "Budget", (head_text("number1"),))
    pg.click("#taskCustomFields .field:has(#cf_date1) .cf-rename"); pg.wait_for_selector("#fieldNameModalBg.open"); pg.keyboard.press("Escape"); pg.wait_for_timeout(100)
    check("Escape closes only the rename dialog — the task dialog and its edits stay", pg.locator("#fieldNameModalBg.open").count() == 0 and pg.locator("#taskModalBg.open").count() == 1 and pg.input_value("#cf_text3") == "typed but unsaved")
    close_dialog()
    check("...unsaved typing was not saved (Cancel)", "text3" not in custom("R1"))
    # validation
    def try_name(col, new):
        if not pg.locator("#fieldNameModalBg.open").count():      # a refused name leaves the dialog open: reuse it
            open_cols(); pg.click(f"#columnsMenu .cols-row:has(input[data-col='{col}']) .cols-rename"); pg.wait_for_selector("#fieldNameModalBg.open")
        pg.fill("#fieldNameInput", new); pg.keyboard.press("Enter"); pg.wait_for_timeout(120)
    try_name("date1", "budget")
    check("a name used by another custom field is refused, case-insensitively (toast; dialog stays open)", "already the name" in pg.inner_text("#toastMsg") and pg.locator("#fieldNameModalBg.open").count() == 1 and head_text("date1") == "Date1", pg.inner_text("#toastMsg"))
    pg.fill("#fieldNameInput", "Start"); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    check("...so is the name of a standard column (Start)", pg.locator("#fieldNameModalBg.open").count() == 1 and head_text("date1") == "Date1")
    pg.fill("#fieldNameInput", "text2"); pg.keyboard.press("Enter"); pg.wait_for_timeout(100)
    check("...and another field's default name (Text2)", pg.locator("#fieldNameModalBg.open").count() == 1)
    pg.fill("#fieldNameInput", "x" * 60); pg.keyboard.press("Enter"); pg.wait_for_timeout(120)
    check("a name is cut to 40 characters", len(pg.evaluate("() => project.fieldNames.date1")) == 40 and pg.get_attribute("#fieldNameInput", "maxlength") == "40" or len(head_text("date1")) <= 41)
    try_name("date1", "  Due  "); check("names are trimmed", pg.evaluate("() => project.fieldNames.date1") == "Due")
    try_name("date1", "Date1"); pg.wait_for_timeout(50)
    check("typing the default name back is the same as resetting it (no override stored)", "date1" not in pg.evaluate("() => project.fieldNames") and head_text("date1") == "Date1")
    try_name("date1", "Due"); open_cols(); pg.click("#columnsMenu .cols-row:has(input[data-col='date1']) .cols-rename"); pg.wait_for_selector("#fieldNameModalBg.open")
    check("'Use default name' is enabled once renamed", not pg.locator("#fieldNameResetBtn").is_disabled())
    pg.click("#fieldNameResetBtn"); pg.wait_for_timeout(120)
    check("...and resets it", head_text("date1") == "Date1" and "date1" not in pg.evaluate("() => project.fieldNames"))
    try_name("date1", "   "); pg.wait_for_timeout(50)
    check("an empty name means the default", head_text("date1") == "Date1")
    # names are user text: escaped everywhere
    try_name("flag1", "<img src=x onerror=window.__pwned=1>"); close_cols(); pg.wait_for_timeout(100)
    open_cols()
    check("a name with markup is shown as plain text in the header, the menu, the filter chip and the dialog — never executed", head_text("flag1") == "<img src=x onerror=window.__pwned=1>" and pg.locator("#gridHeader img, #columnsMenu img").count() == 0 and pg.evaluate("() => window.__pwned") is None)
    close_cols()
    pg.evaluate("() => { colFilters.flag1 = {type: 'values', values: new Set(['Yes']), blanks: false}; render(); }")
    open_dialog("R1"); pg.click("#taskTabBtnCustom")
    check("...also in the filter bar and the dialog tab", pg.locator("#filterBar img, #taskCustomFields img").count() == 0 and "<img" in pg.inner_text("#filterBar") and pg.evaluate("() => window.__pwned") is None)
    close_dialog(); pg.evaluate("() => { colFilters = newColFilters(); render(); }")
    try_name("flag1", "Approved"); close_cols()

    # ================================================================= names belong to the plan
    check("plan A has its names", head_text("text1") == "Cost centre" and head_text("flag1") == "Approved")
    pg.evaluate("() => { switchPlan(createPlanRecord('Plan B', null)); }"); pg.wait_for_timeout(500)
    show("text1", "number1", "flag1")
    check("a second plan starts with the default names", head_text("text1") == "Text1" and head_text("flag1") == "Flag1" and pg.evaluate("() => project.fieldNames") is None, (head_text("text1"), pg.evaluate("() => project.fieldNames")))
    rename_via_menu("text1", "Owner"); close_cols()
    check("...and can name the same field differently", head_text("text1") == "Owner")
    pg.evaluate("() => { const id = JSON.parse(localStorage.getItem('milestone-plans')).plans.find(p => p.name === 'My Project').id; switchPlan(id); }"); pg.wait_for_timeout(500)
    check("switching back: plan A keeps ITS names", head_text("text1") == "Cost centre" and head_text("flag1") == "Approved" and head_text("number1") == "Budget", (head_text("text1"), head_text("number1")))
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(200)
    check("...and both survive a reload", head_text("text1") == "Cost centre")
    # values are per task/per plan too
    pg.evaluate("() => { const id = JSON.parse(localStorage.getItem('milestone-plans')).plans.find(p => p.name === 'Plan B').id; switchPlan(id); }"); pg.wait_for_timeout(500)
    check("plan B's tasks don't show plan A's values (there are none yet)", pg.evaluate("() => tasks.length") == 0 and head_text("text1") == "Owner")
    pg.evaluate("() => { const id = JSON.parse(localStorage.getItem('milestone-plans')).plans.find(p => p.name === 'My Project').id; switchPlan(id); }"); pg.wait_for_timeout(500)

    # ================================================================= filters
    make([{"name": "F1", "extra": {"custom": {"text1": "alpha", "number1": 5, "date1": "2026-09-30", "flag1": True}}}, {"name": "F2", "extra": {"custom": {"text1": "beta", "number1": 20, "date1": "2026-12-01"}}}, {"name": "F3", "extra": {"custom": {"text1": "alphabet", "number1": 12, "flag1": True}}}, {"name": "F4"}])
    show("text1", "number1", "date1", "flag1")
    def flt(col): pg.locator(f".col-filter-btn[data-col='{col}']").click(); pg.wait_for_selector("#filterMenu.open")
    def clear(): pg.evaluate("() => { colFilters = newColFilters(); render(); }")
    flt("text1"); labels = pg.locator("#filterTree .ft-label").all_inner_texts()
    check("Text filter: a value list (with (Blanks)) under the field's own name", labels == ["(Select All)", "alpha", "alphabet", "beta", "(Blanks)"] and "Filter Cost centre" in pg.inner_text("#filterMenu .filter-head"), labels)
    pg.select_option("#filterRuleSel", "begins"); pg.fill("#filterInputA", "alph"); pg.click("#filterOkBtn"); pg.wait_for_timeout(100)
    check("...'begins with alph' -> F1 and F3", set(names()) == {"F1", "F3"}, names())
    check("...its chip carries the custom name", "Cost centre: begins with" in pg.inner_text("#filterBar"), pg.inner_text("#filterBar")); clear()
    flt("number1"); pg.select_option("#filterRuleSel", "between"); pg.fill("#filterInputA", "10"); pg.fill("#filterInputB", "25"); pg.click("#filterOkBtn"); pg.wait_for_timeout(100)
    check("Number filter: between 10 and 25 -> F2 and F3", set(names()) == {"F2", "F3"}, names()); clear()
    flt("date1"); pg.select_option("#filterRuleSel", "before"); pg.fill("#filterInputA", "2026-10-15"); pg.click("#filterOkBtn"); pg.wait_for_timeout(100)
    check("Date filter: before 15.10.2026 -> F1 only (blank dates never match a rule)", set(names()) == {"F1"}, names()); clear()
    flt("flag1"); labels = pg.locator("#filterTree .ft-label").all_inner_texts()
    check("Flag filter: a Yes / No list, Yes first, no rule selector", labels == ["(Select All)", "Yes", "No"] and pg.locator("#filterRuleSel").count() == 0, labels)
    pg.locator("#filterTree .ft-cb[data-key='all']").uncheck(); pg.locator("#filterTree .ft-label:has-text('Yes') .ft-cb").check(); pg.click("#filterOkBtn"); pg.wait_for_timeout(100)
    check("...only the flagged tasks (an unset flag counts as No)", set(names()) == {"F1", "F3"}, names())
    check("...header funnel highlighted, chip 'Approved: Yes'", pg.locator(".col-filter-btn[data-col='flag1'].active").count() == 1 and "Approved: Yes" in pg.inner_text("#filterBar"), pg.inner_text("#filterBar"))
    flt("number1"); labels = pg.locator("#filterTree .ft-label").all_inner_texts()
    check("cascade: with the flag filter on, the Budget list only offers 5 and 12", labels == ["(Select All)", "5", "12"], labels); pg.keyboard.press("Escape"); clear()

    # ================================================================= Excel
    def export(cols, path):
        pg.click("#dataMenuBtn"); pg.click("#excelExportItem"); pg.wait_for_selector("#excelModalBg.open")
        if cols != "shown": pg.check(f"input[name='excelCols'][value='{cols}']")
        pg.set_checked("#excelGantt", False)
        with pg.expect_download() as dl: pg.click("#excelExportBtn")
        dl.value.save_as(path)
    make([{"name": "X1", "extra": {"custom": {"text1": "alpha", "number1": 5.5, "date1": "2026-09-30", "flag1": True}}}, {"name": "X2", "extra": {"custom": {"text1": "beta", "number1": 20}}}])
    pg.evaluate("() => { project.fieldNames = {text1: 'Cost & <centre>', number1: 'Budget'}; save(); render(); }")
    show("text1", "number1", "date1", "flag1")
    export("shown", "cf_shown.xlsx"); ws = openpyxl.load_workbook("cf_shown.xlsx")["Tasks"]; hdr = [c.value for c in ws[4]]
    check("Excel 'as shown': the enabled custom columns follow the list, headed with the plan's names", hdr[-4:] == ["Cost & <centre>", "Budget", "Date1", "Flag1"], hdr)
    col = {h: i + 1 for i, h in enumerate(hdr)}
    check("Excel: Text as text, Number as a real number, Date as a real date, Flag as Yes/No", ws.cell(5, col["Cost & <centre>"]).value == "alpha" and ws.cell(5, col["Budget"]).value == 5.5 and isinstance(ws.cell(5, col["Budget"]).value, float) and ws.cell(5, col["Date1"]).value.date().isoformat() == "2026-09-30" and ws.cell(5, col["Date1"]).number_format == "dd\\.mm\\.yyyy" and ws.cell(5, col["Flag1"]).value == "Yes" and ws.cell(6, col["Flag1"]).value == "No", [ws.cell(5, c).value for c in range(col["Cost & <centre>"], col["Flag1"] + 1)])
    check("...an empty value is an empty cell", ws.cell(6, col["Date1"]).value is None)
    pg.evaluate("() => { for (const c of ['text1','number1','date1','flag1']) colHidden.add(c); save(); render(); }")
    export("shown", "cf_hidden.xlsx"); h2 = [c.value for c in openpyxl.load_workbook("cf_hidden.xlsx")["Tasks"][4]]
    check("hidden custom columns are not exported in 'as shown'", not any(x in h2 for x in ("Budget", "Date1", "Flag1")), h2)
    export("all", "cf_all.xlsx"); h3 = [c.value for c in openpyxl.load_workbook("cf_all.xlsx")["Tasks"][4]]
    check("'All columns' adds only the custom fields in use (or renamed): Cost & <centre>, Budget, Date1, Flag1 — not the 16 empty ones", [x for x in h3 if x in ("Cost & <centre>", "Budget", "Date1", "Flag1")] == ["Cost & <centre>", "Budget", "Date1", "Flag1"] and not any(x in h3 for x in ("Text2", "Number3", "Date5", "Flag4")), h3)
    pg.evaluate("() => { project.fieldNames = {text5: 'Empty but named'}; tasks.forEach(t => delete t.custom); save(); render(); }")
    export("all", "cf_named.xlsx"); h4 = [c.value for c in openpyxl.load_workbook("cf_named.xlsx")["Tasks"][4]]
    check("...a renamed field is included even with no values", "Empty but named" in h4 and "Text1" not in h4, h4)

    # ================================================================= data hygiene, sync
    pg.evaluate("""() => { project.fieldNames = {text1: '  Trimmed  ', bogus: 'x', number1: 5, date1: 'Date1', flag1: 'y'.repeat(60)}; tasks[0].custom = {text1: '  spaced  ', text2: 'z'.repeat(400), number1: '3,5', number2: 'NaN', number3: Infinity, date1: '2026-02-31', date2: '2026-03-04', flag1: 'true', flag2: false, flag3: 0, bogus: 'x'}; tasks[1].custom = 'not an object'; normalizeData(); }""")
    c0 = pg.evaluate("() => tasks[0].custom")
    check("normalisation of stored values: only real fields with valid values survive", c0 == {"text1": "spaced", "text2": "z" * 255, "number1": 3.5, "date2": "2026-03-04", "flag1": True}, c0)
    check("...a custom that isn't an object is dropped", pg.evaluate("() => 'custom' in tasks[1]") is False)
    fn = pg.evaluate("() => project.fieldNames")
    check("normalisation of the names: unknown ids, non-strings and default names dropped, trimmed and capped at 40", fn == {"text1": "Trimmed", "flag1": "y" * 40}, fn)
    pg.evaluate("() => { project.fieldNames = {}; normalizeData(); }")
    check("an empty name map is removed rather than stored", pg.evaluate("() => 'fieldNames' in project") is False)
    pg.evaluate("""() => { project.fieldNames = {text1: 'Old name'}; project.updatedAt = 10; const t = tasks[0]; t.updatedAt = 10; t.custom = {text1: 'old'}; }""")
    pg.evaluate("""() => { const remote = {project: Object.assign({}, project, {fieldNames: {text1: 'Renamed remotely'}, updatedAt: 99}), tasks: [Object.assign({}, JSON.parse(JSON.stringify(tasks[0])), {custom: {text1: 'remote value', flag3: true}, updatedAt: 99})], deletedTaskIds: []}; mergeData(remote); normalizeData(); }""")
    check("a newer copy from another device brings its custom values and its field names with it", pg.evaluate("() => [tasks[0].custom, project.fieldNames]") == [{"text1": "remote value", "flag3": True}, {"text1": "Renamed remotely"}], pg.evaluate("() => [tasks[0].custom, project.fieldNames]"))
    pg.evaluate("""() => { const remote = {project: Object.assign({}, project, {fieldNames: {text1: 'STALE'}, updatedAt: 1}), tasks: [Object.assign({}, JSON.parse(JSON.stringify(tasks[0])), {custom: {text1: 'stale'}, updatedAt: 1})], deletedTaskIds: []}; mergeData(remote); normalizeData(); }""")
    check("...and an older copy does not overwrite them", pg.evaluate("() => [tasks[0].custom.text1, project.fieldNames.text1]") == ["remote value", "Renamed remotely"])
    snap = pg.evaluate("() => { const s = syncPayload(); return [s.tasks[0].custom, s.project.fieldNames]; }")
    check("exports, backups and the plan's file all carry both (syncPayload)", snap == [{"text1": "remote value", "flag3": True}, {"text1": "Renamed remotely"}], snap)
    pg.evaluate("""() => { pendingImportData = {project: {name: 'Imported', updatedAt: 1, fieldNames: {date2: 'Deadline'}}, tasks: [Object.assign({}, JSON.parse(JSON.stringify(tasks[0])), {custom: {date2: '2026-05-05'}})], deletedTaskIds: []}; applyImport('replace'); }""")
    check("Import → Replace restores both the values and the names", pg.evaluate("() => [tasks[0].custom, project.fieldNames]") == [{"date2": "2026-05-05"}, {"date2": "Deadline"}], pg.evaluate("() => [tasks[0].custom, project.fieldNames]"))

    # ================================================================= reordering and reset
    make([{"name": "Solo"}]); pg.evaluate("() => { project.fieldNames = {text1: 'Alpha'}; save(); }")
    show("text1", "text2")
    open_cols(); pg.locator("#columnsMenu .cols-row:has(input[data-col='text2']) .cols-move button").first.click(); pg.wait_for_timeout(100)
    check("custom columns can be reordered like any other (Text2 moved above Text1)", head_cols().index("text2") < head_cols().index("text1"), head_cols())
    pg.click("#columnsMenu .btn-link:has-text('Reset')"); pg.wait_for_timeout(100)
    check("'Reset to default' hides them again and restores the order — but keeps the plan's names", head_cols() == DEFAULT_SHOWN and pg.evaluate("() => project.fieldNames") == {"text1": "Alpha"}, head_cols())

    # ================================================================= dialogs put the cursor in their name field (they fade in, so focus needs a timer)
    pg.click("#planMenuBtn"); pg.click("#planNewItem"); pg.wait_for_selector("#planModalBg.open"); pg.wait_for_timeout(200)
    check("New plan: the cursor is in the name field, selected", pg.evaluate("() => document.activeElement.id") == "planNameInput" and pg.evaluate("() => { const i = document.activeElement; return i.selectionStart === 0 && i.selectionEnd === i.value.length; }"))
    pg.keyboard.press("Escape"); pg.wait_for_timeout(100)
    pg.click("#planMenuBtn"); pg.click("#planRenameItem"); pg.wait_for_selector("#planModalBg.open"); pg.wait_for_timeout(200)
    check("Rename plan: same", pg.evaluate("() => document.activeElement.id") == "planNameInput")
    pg.keyboard.press("Escape"); pg.wait_for_timeout(100)
    open_cols(); pg.click("#columnsMenu .cols-row:has(input[data-col='text3']) .cols-rename"); pg.wait_for_selector("#fieldNameModalBg.open"); pg.wait_for_timeout(200)
    check("Rename field: same, with the current name selected so typing replaces it", pg.evaluate("() => document.activeElement.id") == "fieldNameInput" and pg.evaluate("() => { const i = document.activeElement; return i.selectionStart === 0 && i.selectionEnd === i.value.length; }"))
    pg.keyboard.press("Escape"); close_cols()
    # the default sequence of the column picker (user's order: Predecessors before Remaining Duration and Status)
    pg.evaluate("() => { resetColumns(); }")
    open_cols()
    order = pg.evaluate("() => [...document.querySelectorAll('#columnsMenu input[data-col]')].map(i => i.dataset.col)")
    check("the default column sequence: Mode, WBS, Name, Start, Finish, Actual Start, Actual Finish, Duration, %, Predecessors, Remaining, Status, Resource, the six baseline/variance columns, then the custom fields", order == ["mode", "wbs", "name", "start", "end", "actualStart", "actualFinish", "duration", "progress", "preds", "remaining", "status", "resource", "baselineStart", "baselineFinish", "baselineDuration", "startVariance", "finishVariance", "durationVariance"] + IDS, order)
    close_cols()

    print("console errors/warnings:", errors); print(f"{sum(results)}/{len(results)} passed"); b.close()
