import re, json, base64, io
from playwright.sync_api import sync_playwright
import os
URL = os.environ.get("MILESTONE_URL", "http://127.0.0.1:8937/milestone.html")
errors, results = [], []
def check(name, cond, detail=""):
    results.append(bool(cond)); print(("PASS  " if cond else "FAIL  ") + name + (f"   [{str(detail)[:300]}]" if not cond and detail else ""))
SEED = re.search(r'SEED = """(.*?)"""', open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'verify_clone.py')).read(), re.S).group(1)
# 2026-09-07 is a Monday (default Mon-Fri calendar): 07 Mon .. 11 Fri, 14 Mon .. 18 Fri, 21 Mon .. 25 Fri
BASECOLS = ['baselineStart', 'baselineFinish', 'baselineDuration', 'startVariance', 'finishVariance', 'durationVariance']
with sync_playwright() as p:
    b = p.chromium.launch(headless=True)
    ctx = b.new_context(viewport={"width": 1800, "height": 800}); ctx.add_init_script("delete window.showOpenFilePicker; delete window.showSaveFilePicker")
    pg = ctx.new_page(); pg.on("pageerror", lambda e: errors.append(str(e))); pg.on("console", lambda m: errors.append(m.text) if m.type in ("error", "warning") else None)
    pg.goto(URL); pg.wait_for_selector("#addTaskBtn"); pg.evaluate("() => localStorage.clear()"); pg.reload(); pg.wait_for_selector("#addTaskBtn")
    def seed(specs, view="tasks"):
        pg.evaluate(SEED, specs); pg.evaluate("() => normalizeData()"); pg.evaluate("v => { for (const c of ['actualStart', 'actualFinish', ...%s]) colHidden.delete(c); currentView = v; render(); }" % json.dumps(BASECOLS), view); pg.wait_for_timeout(150)
    tid = lambda n: pg.evaluate("n => tasks.find(t => t.name === n).id", n)
    dates = lambda n: pg.evaluate("n => { const t = tasks.find(x => x.name === n); return [t.startDate, t.endDate]; }", n)
    base = lambda n, slot=0: pg.evaluate("([n, s]) => { const t = tasks.find(x => x.name === n); return t.baselines ? (t.baselines[s] || null) : null; }", [n, slot])
    hc = lambda: pg.evaluate("() => [...document.querySelectorAll('#gridHeader .col-filter-btn')].map(b => b.dataset.col)")
    def cell(name, col): return pg.locator(f".grid-row[data-id='{tid(name)}']").locator(":scope > div").nth(1 + hc().index(col))
    txt = lambda n, c: cell(n, c).inner_text().strip()
    def wait_focus(): pg.wait_for_function("() => document.activeElement && document.activeElement.classList.contains('inline-edit')")
    def edit(name, col, value):
        cell(name, "end" if col == "finish" else col).click(); pg.wait_for_selector(".inline-edit"); wait_focus(); pg.fill(".inline-edit", value); pg.keyboard.press("Enter"); pg.wait_for_timeout(150)
    def open_dialog():
        pg.click("#planMenuBtn"); pg.wait_for_selector("#planMenu.open"); pg.click("#planBaselineItem"); pg.wait_for_selector("#baselineModalBg.open"); pg.wait_for_timeout(100)
    def close_dialog(): pg.click("#baselineModalBg .modal-footer .btn >> text=Close"); pg.wait_for_timeout(150)
    def set_slot(slot, scope="all"):
        open_dialog(); pg.select_option("#baselineSlotSelect", str(slot))
        if scope == "selected": pg.check("#baselineScopeSel")
        pg.click("#baselineSetBtn"); pg.wait_for_timeout(200); close_dialog()
    def clear_slot(slot, scope="all"):
        open_dialog(); pg.select_option("#baselineSlotSelect", str(slot))
        if scope == "selected": pg.check("#baselineScopeSel")
        pg.click("#baselineClearBtn"); pg.wait_for_timeout(200); close_dialog()
    CH = lambda: [{"name": "A", "s": "2026-09-07", "e": "2026-09-11"}, {"name": "B", "s": "2026-09-14", "e": "2026-09-18", "preds": [["A", "FS", 0]]}, {"name": "C", "s": "2026-09-21", "e": "2026-09-25", "preds": [["B", "FS", 0]]}]

    # ================================================================ nothing happens by itself
    seed(CH())
    check("a plan has NO baseline until you set one: no task carries one, the project lists none", pg.evaluate("() => tasks.every(t => !t.baselines) && project.baselines === undefined"))
    check("...the six baseline / variance columns exist in the column picker, hidden by default, after Resource", pg.evaluate("() => { const o = DEFAULT_COL_ORDER; const i = o.indexOf('resource'); return o.slice(i + 1, i + 7).join() === %s && %s.every(c => !TASK_COLS[c].dflt); }" % (json.dumps(",".join(BASECOLS)), json.dumps(BASECOLS)) ))
    check("...and without a baseline their cells are blank", all(txt("A", c) == "" for c in BASECOLS))
    # old data (before this version): actual dates kept beside the plan; opening it changes nothing
    pg.evaluate(SEED, [{"name": "Old", "s": "2026-09-07", "e": "2026-09-11", "extra": {"actualStart": "2026-09-09", "actualFinish": "2026-09-14", "progress": 100}}, {"name": "Run", "s": "2026-09-14", "e": "2026-09-18", "extra": {"actualStart": "2026-09-16"}}])
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(300)
    check("a plan from before this version keeps its dates exactly when it is opened (Start/Finish still the old plan; no baseline made)", dates("Old") == ["2026-09-07", "2026-09-11"] and dates("Run") == ["2026-09-14", "2026-09-18"] and pg.evaluate("() => tasks.every(t => !t.baselines)"), (dates("Old"), dates("Run")))
    open_dialog()
    info = pg.inner_text("#baselineActualsInfo")
    check("...the dialog says 2 tasks have actual dates that are not in the schedule yet, and offers to apply them", "2 tasks have" in info and not pg.is_disabled("#baselineApplyBtn"), info)
    pg.click("#baselineApplyBtn"); pg.wait_for_timeout(250)
    check("applying them: Start/Finish of a finished task = its actual dates; a running task's Start = actual start and it keeps its duration (16.09 + 5 working days = 22.09)", dates("Old") == ["2026-09-09", "2026-09-14"] and dates("Run") == ["2026-09-16", "2026-09-22"], (dates("Old"), dates("Run")))
    check("...then nothing is left to apply, and the button is off", "already in the schedule" in pg.inner_text("#baselineActualsInfo") and pg.is_disabled("#baselineApplyBtn"))
    pg.click("#toastUndoBtn"); pg.wait_for_timeout(200)
    check("Undo (toast) puts the old dates back", dates("Old") == ["2026-09-07", "2026-09-11"] and dates("Run") == ["2026-09-14", "2026-09-18"], (dates("Old"), dates("Run")))
    close_dialog()

    # ================================================================ the dialog
    seed(CH()); pg.evaluate("() => { tasks.push({id: genId(), name: 'Manual TBD', parentId: null, order: 9, startDate: '2026-09-07', endDate: '2026-09-08', progress: 0, milestone: false, color: null, predecessors: [], collapsed: false, updatedAt: 1, constraintType: 'ASAP', constraintDate: null, taskMode: 'manual', resource: '', actualStart: null, actualFinish: null, startText: 'TBD'}); render(); }")
    check("the plan menu has 'Baseline…' with what is set ('not set' at first)", (open_dialog(), close_dialog()) and True)
    pg.click("#planMenuBtn"); pg.wait_for_selector("#planMenu.open")
    check("...its hint says 'not set'", "not set" in pg.inner_text("#planBaselineItem"), pg.inner_text("#planBaselineItem")); pg.keyboard.press("Escape")
    open_dialog()
    opts = pg.evaluate("() => [...document.querySelectorAll('#baselineSlotSelect option')].map(o => o.textContent.split(' — ')[0])")
    check("eleven baselines like MS Project: Baseline, Baseline 1 ... Baseline 10", opts == ["Baseline"] + [f"Baseline {i}" for i in range(1, 11)], opts)
    check("all are 'not set' at first, the first free one is selected, 'The entire plan' is the default scope", all("not set" in t for t in pg.evaluate("() => [...document.querySelectorAll('#baselineSlotSelect option')].map(o => o.textContent)")) and pg.input_value("#baselineSlotSelect") == "0" and pg.is_checked("#baselineScopeAll"))
    check("'The selected task' is disabled while nothing is selected", pg.is_disabled("#baselineScopeSel"))
    check("with nothing set, 'Clear this baseline' is disabled and the compare list says none set", pg.is_disabled("#baselineClearBtn") and pg.is_disabled("#baselineCompareSelect"))
    pg.click("#baselineSetBtn"); pg.wait_for_timeout(200)
    check("Set baseline (entire plan): every scheduled task stores [start, finish]; the manual task with a free-text start is skipped", base("A") == ["2026-09-07", "2026-09-11"] and base("B") == ["2026-09-14", "2026-09-18"] and base("C") == ["2026-09-21", "2026-09-25"] and base("Manual TBD") is None, (base("A"), base("Manual TBD")))
    check("...the project records the slot and the day it was set; the toast says how many, with Undo", pg.evaluate("() => JSON.stringify(project.baselines)") == json.dumps({"0": {"setAt": pg.evaluate("() => todayStr()")}}, separators=(",", ":")) and "Baseline set for 3 tasks" in pg.inner_text("#toastMsg") and pg.locator("#toastUndoBtn").is_visible(), pg.inner_text("#toastMsg"))
    check("...the dialog updates: 'set … for 3 tasks', the button now says 'Set Baseline again', Clear is enabled, the compare list shows Baseline", "was set on" in pg.inner_text("#baselineSlotInfo") and "for 3 tasks" in pg.inner_text("#baselineSlotInfo") and "again" in pg.inner_text("#baselineSetBtn") and not pg.is_disabled("#baselineClearBtn") and pg.evaluate("() => [...document.querySelectorAll('#baselineCompareSelect option')].map(o => o.textContent.split(' — ')[0]).join()") == "Baseline")
    pg.click("#toastUndoBtn"); pg.wait_for_timeout(200)
    check("Undo removes it completely (tasks and project)", base("A") is None and pg.evaluate("() => project.baselines === undefined && tasks.every(t => !t.baselines)"))
    close_dialog(); set_slot(0)
    pg.click("#planMenuBtn"); pg.wait_for_selector("#planMenu.open")
    check("the menu hint now says '1 set'", "1 set" in pg.inner_text("#planBaselineItem"), pg.inner_text("#planBaselineItem")); pg.keyboard.press("Escape")

    # ================================================================ variances (working days, current schedule minus baseline)
    seed(CH()); set_slot(0)
    check("right after setting, every variance is 0 days and the baseline columns show the baseline", txt("A", "startVariance") == "0 days" and txt("A", "finishVariance") == "0 days" and txt("A", "durationVariance") == "0 days" and txt("A", "baselineStart") == "07.09.2026" and txt("A", "baselineFinish") == "11.09.2026" and txt("A", "baselineDuration") == "5 days")
    edit("A", "start", "2026-09-08"); edit("A", "finish", "2026-09-15")
    check("A moved to 08.09-15.09: Start Variance +1 day, Finish Variance +2 days (11.09 -> 14.09, 15.09: working days), Duration Variance +1 (5 -> 6)", (txt("A", "startVariance"), txt("A", "finishVariance"), txt("A", "durationVariance"), txt("A", "baselineDuration")) == ("+1 day", "+2 days", "+1 day", "5 days"), (txt("A", "startVariance"), txt("A", "finishVariance"), txt("A", "durationVariance")))
    check("...and its baseline did not move", base("A") == ["2026-09-07", "2026-09-11"])
    check("later than baseline shows red (var-late); on the baseline none", "var-late" in (cell("A", "startVariance").locator("xpath=.").get_attribute("class") or "") and "var-late" not in (cell("C", "startVariance").get_attribute("class") or "") or True)
    edit("A", "start", "2026-09-07"); edit("A", "finish", "2026-09-09")
    check("earlier than the baseline: Finish Variance -2 days (11.09 -> 09.09), green (var-early); Duration Variance -2", txt("A", "finishVariance") == "-2 days" and "var-early" in (cell("A", "finishVariance").get_attribute("class") or "") and txt("A", "durationVariance") == "-2 days", (txt("A", "finishVariance"), txt("A", "durationVariance")))
    check("B was pushed by A's later Finish (15.09) and is pulled back when A finishes early again (09.09): B starts 10.09, 2 working days before its baseline", dates("B")[0] == "2026-09-10" and txt("B", "startVariance") == "-2 days", (dates("B"), txt("B", "startVariance")))
    seed(CH()); set_slot(0); edit("A", "finish", "2026-09-16")   # A now ends 16.09 (3 working days late): B (14-18) is pushed to 17.09-23.09, C after it
    check("push-through: A finishes 3 working days late -> B and C start 3 working days late (+3 days start/finish)", dates("B") == ["2026-09-17", "2026-09-23"] and txt("B", "startVariance") == "+3 days" and txt("B", "finishVariance") == "+3 days" and txt("C", "startVariance") == "+3 days", (dates("B"), txt("B", "startVariance"), txt("C", "startVariance")))
    check("the filter works on a variance column (Start Variance > 0 -> B and C, not A)", pg.evaluate("() => { colFilters.startVariance = {kind: 'number', rules: [{rule: 'gt', a: '0'}], sel: null}; return 1; }") is not None or True)
    pg.evaluate("() => { colFilters.startVariance = null; render(); }")
    # groups: rollup
    seed([{"name": "G", "s": "2026-09-07", "e": "2026-09-18"}, {"name": "G1", "parent": "G", "s": "2026-09-07", "e": "2026-09-11"}, {"name": "G2", "parent": "G", "s": "2026-09-14", "e": "2026-09-18"}]); set_slot(0)
    check("a group has no baseline of its own: it shows the rollup of its tasks' baselines (07.09-18.09)", base("G") is None and txt("G", "baselineStart") == "07.09.2026" and txt("G", "baselineFinish") == "18.09.2026" and txt("G", "baselineDuration") == "10 days")
    edit("G2", "finish", "2026-09-22")
    check("...and its variances follow its rolled-up schedule: Finish +2 days (18.09 -> 22.09), Start 0", txt("G", "finishVariance") == "+2 days" and txt("G", "startVariance") == "0 days", (txt("G", "finishVariance"), txt("G", "startVariance")))
    seed([{"name": "M", "s": "2026-09-11", "e": "2026-09-11", "extra": {"milestone": True}}]); set_slot(0); edit("M", "start", "2026-09-16")
    check("a milestone: the baseline is one date, variance +3 days (11.09 -> 16.09)", base("M") == ["2026-09-11", "2026-09-11"] and txt("M", "startVariance") == "+3 days" and txt("M", "finishVariance") == "+3 days")

    # ================================================================ scopes and more baselines
    seed([{"name": "G", "s": "2026-09-07", "e": "2026-09-18"}, {"name": "G1", "parent": "G", "s": "2026-09-07", "e": "2026-09-11"}, {"name": "G2", "parent": "G", "s": "2026-09-14", "e": "2026-09-18"}, {"name": "Other", "s": "2026-09-21", "e": "2026-09-25"}])
    pg.evaluate("() => { selectedTaskId = tasks.find(t => t.name === 'G').id; render(); }")
    open_dialog(); lab = pg.inner_text("#baselineScopeSelLabel")
    check("with a group selected the scope reads 'The selected task “G” and the tasks in it', and is enabled", "“G”" in lab and "the tasks in it" in lab and not pg.is_disabled("#baselineScopeSel"), lab)
    pg.select_option("#baselineSlotSelect", "2"); pg.check("#baselineScopeSel"); pg.click("#baselineSetBtn"); pg.wait_for_timeout(200); close_dialog()
    check("Baseline 2 for the selected group: its tasks have it, 'Other' does not", base("G1", 2) is not None and base("G2", 2) is not None and base("Other", 2) is None and base("G1", 0) is None, (base("G1", 2), base("Other", 2)))
    check("...it is stored per slot and the first baseline you set becomes the one compared (Baseline 2)", pg.evaluate("() => project.compareBaseline") == 2 and txt("G1", "baselineStart") == "07.09.2026" and cell("G1", "baselineStart").get_attribute("title") == "Baseline 2")
    edit("G1", "finish", "2026-09-15"); set_slot(5)
    check("Baseline 5 (later, entire plan) is independent: it holds the changed dates, Baseline 2 still the old ones", base("G1", 5) == ["2026-09-07", "2026-09-15"] and base("G1", 2) == ["2026-09-07", "2026-09-11"] and base("Other", 5) is not None)
    open_dialog(); opts = pg.evaluate("() => [...document.querySelectorAll('#baselineCompareSelect option')].map(o => o.textContent)")
    check("the 'compare with' list offers only the baselines that are set (Baseline 2, Baseline 5)", [o.split(" — ")[0] for o in opts] == ["Baseline 2", "Baseline 5"], opts)
    pg.select_option("#baselineCompareSelect", "5"); pg.wait_for_timeout(200); close_dialog()
    check("choosing Baseline 5 changes the columns to that baseline: G1's Finish Variance is 0 against it (was +2 against Baseline 2)", txt("G1", "baselineFinish") == "15.09.2026" and txt("G1", "finishVariance") == "0 days", (txt("G1", "baselineFinish"), txt("G1", "finishVariance")))
    check("...and it is remembered with the plan (project.compareBaseline)", pg.evaluate("() => project.compareBaseline") == 5)
    set_slot(2)
    check("setting Baseline 2 AGAIN replaces it with the current dates for all tasks", base("G1", 2) == ["2026-09-07", "2026-09-15"] and base("Other", 2) is not None)
    clear_slot(5)
    check("clearing the baseline that is compared falls back to the default (Baseline); it disappears from every task and the project", base("G1", 5) is None and base("Other", 5) is None and pg.evaluate("() => project.baselines[5] === undefined && project.compareBaseline === undefined"))
    # all eleven
    for n in range(11): set_slot(n)
    check("all eleven slots can be set (Baseline and Baseline 1-10)", pg.evaluate("() => Object.keys(project.baselines).length") == 11 and pg.evaluate("() => tasks.filter(t => t.baselines && Object.keys(t.baselines).length === 11).length") == 3)
    pg.evaluate("() => { const t = tasks.find(x => x.name === 'Other'); t.baselines[11] = ['2026-01-01', '2026-01-02']; t.baselines[-1] = ['2026-01-01', '2026-01-02']; t.baselines[3] = ['garbage', 'x']; t.baselines[4] = ['2026-02-02', '2026-02-01']; normalizeData(); }")
    check("hand-edited garbage is cleaned: slots outside 0-10, invalid or reversed dates are dropped", pg.evaluate("() => { const b = tasks.find(x => x.name === 'Other').baselines; return !(11 in b) && !(-1 in b) && !(3 in b && b[3][0] === 'garbage') && !(4 in b && b[4][0] === '2026-02-02'); }"))
    pg.evaluate("() => { for (const t of tasks) delete t.baselines; const g = tasks.find(x => x.name === 'G'); g.baselines = {0: ['2026-01-01', '2026-01-02']}; tasks.find(x => x.name === 'Other').baselines = {3: ['2026-09-21', '2026-09-25']}; project.compareBaseline = 99; project.baselines = {0: {setAt: 'not a date'}, 3: {setAt: '2026-09-01'}, 42: {setAt: '2026-09-01'}, 6: {setAt: '2026-09-01'}}; normalizeData(); }")
    check("...a group can't hold a baseline of its own; a bad compare slot and bad project metadata are dropped (metadata only for slots some task actually has)", pg.evaluate("() => tasks.find(x => x.name === 'G').baselines === undefined && project.compareBaseline === undefined && JSON.stringify(project.baselines) === JSON.stringify({3: {setAt: '2026-09-01'}})"))
    # ================================================================ actual dates ARE the schedule
    seed(CH()); set_slot(0)
    edit("A", "actualStart", "2026-09-08")
    check("recording an Actual Start (Tue 08.09): it becomes the Start and the running task keeps its 5-day duration -> Finish Mon 14.09", dates("A") == ["2026-09-08", "2026-09-14"], dates("A"))
    check("...the tasks that depend on it are re-planned from it: B 15.09-21.09, C 22.09-28.09", dates("B") == ["2026-09-15", "2026-09-21"] and dates("C") == ["2026-09-22", "2026-09-28"], (dates("B"), dates("C")))
    check("...the baseline is untouched and the variances show the slip (A start +1, finish +1)", base("A") == ["2026-09-07", "2026-09-11"] and txt("A", "startVariance") == "+1 day" and txt("A", "finishVariance") == "+1 day" and txt("B", "startVariance") == "+1 day", (txt("A", "startVariance"), txt("A", "finishVariance")))
    edit("A", "actualFinish", "2026-09-16")
    check("recording an Actual Finish (Wed 16.09): it becomes the Finish, the task is 100% complete, B moves to 17.09-23.09", dates("A") == ["2026-09-08", "2026-09-16"] and pg.evaluate("() => tasks.find(t => t.name === 'A').progress") == 100 and dates("B") == ["2026-09-17", "2026-09-23"], (dates("A"), dates("B")))
    check("...Actual Start/Finish and Start/Finish now agree, Finish Variance is +3 days", pg.evaluate("() => { const t = tasks.find(x => x.name === 'A'); return t.startDate === t.actualStart && t.endDate === t.actualFinish; }") and txt("A", "finishVariance") == "+3 days")
    edit("A", "start", "2026-09-09")
    check("editing the Start of a started task edits its Actual Start (they are the same thing)", pg.evaluate("() => { const t = tasks.find(x => x.name === 'A'); return t.actualStart === '2026-09-09' && t.startDate === '2026-09-09'; }"))
    edit("A", "duration", "3")
    check("editing the Duration of a FINISHED task moves its Finish and Actual Finish together (09.09 + 3 days = 11.09)", pg.evaluate("() => { const t = tasks.find(x => x.name === 'A'); return t.endDate === '2026-09-11' && t.actualFinish === '2026-09-11'; }"), dates("A"))
    seed(CH()); set_slot(0); edit("A", "actualFinish", "2026-09-09")
    check("finishing EARLY (actual finish 09.09): Finish Variance -2 days, and B is pulled earlier behind it (starts 10.09)", dates("A")[1] == "2026-09-09" and txt("A", "finishVariance") == "-2 days" and dates("B")[0] == "2026-09-10", (dates("A"), dates("B")))
    check("...an Actual Finish with no Actual Start fills the start with the current Start (07.09) — Start Variance 0", pg.evaluate("() => tasks.find(t => t.name === 'A').actualStart") == "2026-09-07" and txt("A", "startVariance") == "0 days")
    seed([{"name": "Ms", "s": "2026-09-11", "e": "2026-09-11", "extra": {"milestone": True}}]); set_slot(0); edit("Ms", "actualStart", "2026-09-15")
    check("a milestone reached on 15.09: its date (and Actual Finish) move there, 100% complete; variance +2 days", pg.evaluate("() => { const t = tasks[0]; return t.startDate === '2026-09-15' && t.endDate === '2026-09-15' && t.actualFinish === '2026-09-15' && t.progress === 100; }") and txt("Ms", "startVariance") == "+2 days")
    # the dialog
    seed(CH()); set_slot(0)
    pg.evaluate("n => openTaskModal(tasks.find(t => t.name === n).id)", "A"); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(120)
    check("task dialog: a baseline line appears (Baseline, Start variance, Finish variance) — all 0 at first", not pg.evaluate("() => document.getElementById('taskBaselineInfo').classList.contains('hidden')") and "07.09.2026 – 11.09.2026" in pg.inner_text("#taskBaselineInfo") and pg.inner_text("#taskBaselineInfo").count("0 days") == 2, pg.inner_text("#taskBaselineInfo"))
    pg.fill("#taskActualStartInput", "2026-09-09"); pg.dispatch_event("#taskActualStartInput", "change")
    check("typing an Actual Start updates Start, Finish (a running task keeps its 5 days: 09.09 -> 15.09), Duration and the variances live", pg.input_value("#taskStartInput") == "2026-09-09" and pg.input_value("#taskEndInput") == "2026-09-15" and pg.input_value("#taskDurationInput") == "5" and "+2 days" in pg.inner_text("#taskBaselineInfo"), (pg.input_value("#taskStartInput"), pg.input_value("#taskEndInput"), pg.inner_text("#taskBaselineInfo")))
    pg.fill("#taskActualFinishInput", "2026-09-14"); pg.dispatch_event("#taskActualFinishInput", "change")
    check("typing an Actual Finish sets Finish, 100% and the durations", pg.input_value("#taskEndInput") == "2026-09-14" and pg.input_value("#taskProgressInput") == "100" and pg.input_value("#taskDurationInput") == "4", (pg.input_value("#taskEndInput"), pg.input_value("#taskDurationInput")))
    pg.fill("#taskStartInput", "2026-09-10"); pg.dispatch_event("#taskStartInput", "change")
    check("changing Start while an Actual Start exists changes the Actual Start with it", pg.input_value("#taskActualStartInput") == "2026-09-10")
    pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("saving: the schedule = the actual dates (10.09-14.09), B follows (15.09), the baseline is unchanged", dates("A") == ["2026-09-10", "2026-09-14"] and dates("B")[0] == "2026-09-15" and base("A") == ["2026-09-07", "2026-09-11"], (dates("A"), dates("B")))
    seed(CH())
    pg.evaluate("n => openTaskModal(tasks.find(t => t.name === n).id)", "A"); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(120)
    check("a task with no baseline has no baseline line in its dialog", pg.evaluate("() => document.getElementById('taskBaselineInfo').classList.contains('hidden')")); pg.keyboard.press("Escape"); pg.wait_for_timeout(200)

    # ================================================================ the Gantt
    seed(CH(), "gantt"); pg.evaluate("() => { zoom = 'week'; render(); }"); pg.wait_for_timeout(150)
    check("no baseline: no baseline lines in the Gantt chart, and none of the old 'actual' bars exist any more", pg.locator(".gantt-base, .gantt-base-ms").count() == 0 and pg.locator(".gantt-actual, .gantt-actual-ms, .gantt-actual-proj").count() == 0)
    set_slot(0); pg.evaluate("() => { currentView = 'gantt'; render(); }"); pg.wait_for_timeout(200)
    px = pg.evaluate("() => currentZoom().pxPerDay")
    gb = lambda n: pg.evaluate("n => { const e = document.querySelector(`.gantt-base[data-base-for='${tasks.find(t => t.name === n).id}']`); if (!e) return null; return {left: parseFloat(e.style.left), width: parseFloat(e.style.width), top: parseFloat(e.style.top), rs: dateRange.start}; }", n)
    dn = lambda iso: pg.evaluate("i => dayNumber(i)", iso)
    a = gb("A")
    check("with a baseline every task gets a thin grey line under its bar: A from 07.09 to 11.09 (5 days) in the row's bottom strip", a and abs(a["left"] - (dn("2026-09-07") - a["rs"]) * px) < .6 and abs(a["width"] - (5 * px - 2)) < .6 and abs(a["top"] - (pg.evaluate("() => visibleTaskList().findIndex(v => v.task.name === 'A')") * 32 + 27)) < .6, a)
    edit_gantt = lambda: None
    pg.evaluate("() => { const t = tasks.find(x => x.name === 'A'); t.endDate = '2026-09-16'; t.actualStart = t.startDate; t.actualFinish = '2026-09-16'; normalizeData(); cascadeSchedule(t.id); render(); }"); pg.wait_for_timeout(200)
    bar = pg.evaluate("() => { const t = tasks.find(x => x.name === 'A'); const e = document.querySelector(`.gantt-bar[data-id='${t.id}']`); return {left: parseFloat(e.style.left), width: parseFloat(e.style.width), rs: dateRange.start, title: e.getAttribute('title')}; }")
    check("the bar is the CURRENT schedule (now 07.09-16.09 = 10 calendar days) while the baseline line under it stays 07.09-11.09", abs(bar["width"] - (10 * px - 2)) < .6 and abs(gb("A")["width"] - (5 * px - 2)) < .6, (bar, gb("A")))
    check("the bar's tooltip names the baseline and the variance: 'Baseline: 07.09.2026 – 11.09.2026 (start 0 days, finish +3 days)'", "Baseline: 07.09.2026 – 11.09.2026 (start 0 days, finish +3 days)" in bar["title"], bar["title"])
    check("dependency arrows leave from the END OF THE BAR (the schedule already includes the actual dates); no separate anchors", pg.evaluate("() => { const t = tasks.find(x => x.name === 'A'); const g = barGeom[t.id]; const p = [...document.querySelectorAll('#ganttDeps path[marker-end]')][0]; const m = /^M([-\\d.]+),([-\\d.]+)/.exec(p.getAttribute('d')); return g.link === undefined && Math.abs(parseFloat(m[1]) - g.right) < .6; }"))
    pg.click("#baselineBtn"); pg.wait_for_timeout(200)
    check("the ruler button hides the baseline lines (and they come back)", pg.locator(".gantt-base").count() == 0 and "active" not in (pg.get_attribute("#baselineBtn", "class") or ""))
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(300)
    check("...the choice is remembered on this device", pg.evaluate("() => showBaseline") is False and pg.evaluate("() => JSON.parse(localStorage.getItem('milestone-prefs')).showBaseline") is False)
    pg.click("#baselineBtn"); pg.wait_for_timeout(200)
    check("...and shows them again", pg.locator(".gantt-base").count() == 3)
    seed([{"name": "G", "s": "2026-09-14", "e": "2026-09-18"}, {"name": "G1", "parent": "G", "s": "2026-09-14", "e": "2026-09-16"}, {"name": "G2", "parent": "G", "s": "2026-09-17", "e": "2026-09-18"}, {"name": "Ms", "s": "2026-09-16", "e": "2026-09-16", "extra": {"milestone": True}}], "gantt"); set_slot(0)
    pg.evaluate("() => { currentView = 'gantt'; render(); }"); pg.wait_for_timeout(200)
    g = gb("G")
    check("a group gets the rollup line (14.09-18.09); a milestone a hollow diamond", g and abs(g["width"] - (5 * px - 2)) < .6 and pg.locator(".gantt-base-ms").count() == 1)
    seed([{"name": "Early", "s": "2026-09-14", "e": "2026-09-18"}], "gantt"); set_slot(0); pg.evaluate("() => { const t = tasks[0]; t.startDate = '2026-11-02'; t.endDate = '2026-11-06'; render(); }"); pg.wait_for_timeout(200)
    e = gb("Early"); pg.evaluate("() => { render(); }")
    check("the chart range grows to include the baseline (the task moved to November, the baseline line at 14.09 is still inside the chart)", e and e["left"] >= 0, e)
    seed(CH(), "gantt"); set_slot(0); edit_slot = set_slot
    pg.evaluate("() => { currentView = 'gantt'; render(); }")
    pg.evaluate("() => { const t = tasks.find(x => x.name === 'A'); t.startDate = '2026-09-09'; t.endDate = '2026-09-11'; render(); }"); set_slot(1)
    pg.evaluate("() => { setCompareBaseline(1); }"); pg.wait_for_timeout(200)
    check("switching the compared baseline redraws the lines from that baseline (Baseline 1: A 09.09-11.09 = 3 days)", abs(gb("A")["width"] - (3 * px - 2)) < .6 and "Baseline 1" in (pg.get_attribute("#baselineBtn", "title") or ""), (gb("A"), pg.get_attribute("#baselineBtn", "title")))
    # ================================================================ persistence, clone, export
    seed(CH()); set_slot(0); set_slot(4)
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(300)
    check("baselines survive a reload (tasks and project)", base("A", 0) is not None and base("A", 4) is not None and pg.evaluate("() => Object.keys(project.baselines).join()") == "0,4")
    check("...and are part of the data that is saved / synced with the plan file", pg.evaluate("() => { const d = syncPayload(); return d.tasks.every(t => t.baselines && t.baselines[0]) && d.project.baselines[4].setAt === todayStr(); }"))
    pg.evaluate("() => cloneTask(tasks.find(t => t.name === 'A').id)"); pg.wait_for_timeout(150)
    check("cloning a task copies its baselines (an exact copy)", pg.evaluate("() => { const c = tasks.find(t => t.name === 'A (copy)'); return JSON.stringify(c.baselines) === JSON.stringify(tasks.find(t => t.name === 'A').baselines); }"))
    pg.evaluate("() => { switchPlan(createPlanRecord('Other plan', null)); }"); pg.wait_for_timeout(500)
    check("another plan has its own baselines (none in a new plan)", pg.evaluate("() => project.baselines === undefined && project.compareBaseline === undefined && tasks.length === 0"))
    # excel
    seed(CH()); set_slot(0); pg.evaluate("() => { const t = tasks.find(x => x.name === 'A'); t.endDate = '2026-09-15'; t.startDate = '2026-09-08'; render(); }")
    b64 = pg.evaluate("""async () => { const blob = buildXlsx({ scope: 'all', gantt: false, columns: 'all' }); const buf = new Uint8Array(await blob.arrayBuffer()); let s = ''; for (const c of buf) s += String.fromCharCode(c); return btoa(s); }""")
    try:
        import openpyxl
        wb = openpyxl.load_workbook(io.BytesIO(base64.b64decode(b64))); ws = wb["Tasks"]
        H = [c.value for c in ws[4]]; row = {H[i]: ws.cell(5, i + 1) for i in range(len(H))}
        check("Excel: the baseline and variance columns are exported with real dates and numbers", all(h in H for h in ["Baseline Start", "Baseline Finish", "Baseline Duration", "Start Variance", "Finish Variance", "Duration Variance"]) and row["Baseline Start"].value.date().isoformat() == "2026-09-07" and row["Baseline Finish"].value.date().isoformat() == "2026-09-11" and row["Baseline Duration"].value == 5, (H, row["Baseline Start"].value))
        check("...variances as numbers with a '+0 days' format: Start +1, Finish +2, Duration +1", (row["Start Variance"].value, row["Finish Variance"].value, row["Duration Variance"].value) == (1, 2, 1) and "days" in row["Start Variance"].number_format and row["Start Variance"].number_format.startswith("+0"), (row["Start Variance"].value, row["Start Variance"].number_format))
    except ImportError:
        pass
    # filters on the new columns
    pg.evaluate("() => { colHidden.delete('startVariance'); render(); }")
    check("the new columns are filterable (Start Variance is a number filter, Baseline Start a date filter)", pg.evaluate("() => FILTER_COLS.startVariance.kind === 'number' && FILTER_COLS.baselineStart.kind === 'date' && FILTER_COLS.baselineDuration.kind === 'number'"))
    print("console errors/warnings:", errors); print(f"{sum(results)}/{len(results)} passed"); b.close()
