import re, json
from playwright.sync_api import sync_playwright
import os
URL = os.environ.get("MILESTONE_URL", "http://127.0.0.1:8937/milestone.html")
errors, results = [], []
def check(name, cond, detail=""):
    results.append(bool(cond)); print(("PASS  " if cond else "FAIL  ") + name + (f"   [{str(detail)[:300]}]" if not cond and detail else ""))
SEED = re.search(r'SEED = """(.*?)"""', open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'verify_clone.py')).read(), re.S).group(1)
# 2026-09-07 is a Monday: 07 Mon 08 Tue 09 Wed 10 Thu 11 Fri 12 Sat 13 Sun 14 Mon 15 Tue 16 Wed 17 Thu 18 Fri 19 Sat 21 Mon
with sync_playwright() as p:
    b = p.chromium.launch(headless=True)
    ctx = b.new_context(viewport={"width": 1600, "height": 800}); ctx.add_init_script("delete window.showOpenFilePicker; delete window.showSaveFilePicker; delete window.showDirectoryPicker")
    pg = ctx.new_page(); pg.on("pageerror", lambda e: errors.append(str(e))); pg.on("console", lambda m: errors.append(m.text) if m.type in ("error", "warning") else None)
    pg.goto(URL); pg.wait_for_selector("#addTaskBtn"); pg.evaluate("() => localStorage.clear()"); pg.reload(); pg.wait_for_selector("#addTaskBtn")
    seed = lambda specs: (pg.evaluate(SEED, specs), pg.wait_for_timeout(100))
    tid = lambda n: pg.evaluate("n => tasks.find(t => t.name === n).id", n)
    dates = lambda n: pg.evaluate("n => { const t = tasks.find(x => x.name === n); return [t.startDate, t.endDate]; }", n)
    dur = lambda n: pg.evaluate("n => { const t = tasks.find(x => x.name === n); return durationDays(t.startDate, t.endDate); }", n)
    hc = lambda: pg.evaluate("() => [...document.querySelectorAll('#gridHeader .col-filter-btn')].map(b => b.dataset.col)")
    def cell(name, col): return pg.locator(f".grid-row[data-id='{tid(name)}']").locator(":scope > div").nth(1 + hc().index(col))
    def wait_focus(): pg.wait_for_function("() => document.activeElement && document.activeElement.classList.contains('inline-edit')")
    def edit(name, col, value):
        cell(name, "end" if col == "finish" else col).click(); pg.wait_for_selector(".inline-edit"); wait_focus()
        pg.fill(".inline-edit", value); pg.keyboard.press("Enter"); pg.wait_for_timeout(150)
    A = {"name": "A", "s": "2026-09-07", "e": "2026-09-11"}

    # ================================================================ the default
    check("default calendar: Monday to Friday, nothing stored in the plan", pg.evaluate("() => currentWorkDays().join()") == "1,2,3,4,5" and pg.evaluate("() => calendarLabel()") == "Mon–Fri" and pg.evaluate("() => project.workDays === undefined"))
    seed([A, {"name": "Wk", "s": "2026-09-07", "e": "2026-09-14"}, {"name": "Sun", "s": "2026-09-07", "e": "2026-09-20"}, {"name": "Off", "s": "2026-09-19", "e": "2026-09-20"}])
    check("duration counts working days: Mon-Fri = 5, Mon to the next Monday = 6, over two weeks (to a Sunday) = 10", dur("A") == 5 and dur("Wk") == 6 and dur("Sun") == 10, (dur("A"), dur("Wk"), dur("Sun")))
    check("...a task entirely on days off still counts as 1 day (never 0)", dur("Off") == 1)
    check("...the Duration cell shows it", cell("Wk", "duration").inner_text().strip() == "6 days" and cell("A", "duration").inner_text().strip() == "5 days")
    check("dates already in the plan are not touched by the calendar", dates("Sun") == ["2026-09-07", "2026-09-20"] and dates("Off") == ["2026-09-19", "2026-09-20"])
    # ================================================================ editing durations
    seed([A])
    edit("A", "duration", "6")
    check("Duration 6 from Monday finishes the next Monday (skips the weekend)", dates("A") == ["2026-09-07", "2026-09-14"], dates("A"))
    edit("A", "duration", "10")
    check("Duration 10 from Monday finishes on Friday of the second week", dates("A") == ["2026-09-07", "2026-09-18"], dates("A"))
    edit("A", "duration", "1")
    check("Duration 1 = one working day", dates("A") == ["2026-09-07", "2026-09-07"], dates("A"))
    # ================================================================ dependencies
    def chain(type_="FS", lag=0, b_dur_end="2026-09-10"):
        return [A, {"name": "B", "s": "2026-09-08", "e": b_dur_end, "preds": [["A", type_, lag]]}, {"name": "C", "s": "2026-09-10", "e": "2026-09-10", "preds": [["B", "FS", 0]]}]
    seed(chain()); pg.evaluate("() => applyConstraints(tasks.find(t => t.name === 'B').id)")
    check("FS: the successor of a task finishing Friday starts the next MONDAY, keeping its 3 working days (Mon-Wed)", dates("B") == ["2026-09-14", "2026-09-16"], dates("B"))
    check("...and the chain follows (C on Thursday)", dates("C") == ["2026-09-17", "2026-09-17"], dates("C"))
    for lag, want, label in ((2, "2026-09-16", "FS + 2 working days (Mon + 2 = Wed)"), (-1, "2026-09-11", "FS - 1 working day (a lead: back to Friday, over the weekend)"), (5, "2026-09-21", "FS + 5 working days (a whole week)")):
        seed(chain("FS", lag)); pg.evaluate("() => applyConstraints(tasks.find(t => t.name === 'B').id)")
        check(label, dates("B")[0] == want, dates("B"))
    seed(chain("SS", 2)); pg.evaluate("() => applyConstraints(tasks.find(t => t.name === 'B').id)")
    check("SS + 2 working days: starts Wednesday 09.09", dates("B")[0] == "2026-09-09", dates("B"))
    seed(chain("FF", 0)); pg.evaluate("() => applyConstraints(tasks.find(t => t.name === 'B').id)")
    check("FF: B (3 days) may not finish before A does (Fri 11.09) -> Wed-Fri", dates("B") == ["2026-09-09", "2026-09-11"], dates("B"))
    seed(chain("FF", 1)); pg.evaluate("() => applyConstraints(tasks.find(t => t.name === 'B').id)")
    check("FF + 1: the finish is the next working day after Friday = Monday 14.09 (start Thursday 10.09... over the weekend)", dates("B") == ["2026-09-10", "2026-09-14"], dates("B"))
    seed([A, {"name": "B", "s": "2026-09-08", "e": "2026-09-10", "preds": [["A", "SF", 0]]}]); pg.evaluate("() => applyConstraints(tasks.find(t => t.name === 'B').id)")
    check("SF: B finishes when A starts (Mon 07.09): B (3 days) is pulled earlier to Thu 03.09 - Mon 07.09", dates("B") == ["2026-09-03", "2026-09-07"], dates("B"))
    # actual dates and projection across a weekend
    seed(chain()); pg.evaluate("() => { const a = tasks.find(t => t.name === 'A'); a.actualStart = '2026-09-10'; cascadeSchedule(a.id); }")
    check("started late on Thursday 10.09: projected finish = 5 working days from then = Wed 16.09, so B starts Thu 17.09", pg.evaluate("() => linkEnd(tasks.find(t => t.name === 'A'))") == "2026-09-16" and dates("B")[0] == "2026-09-17", (pg.evaluate("() => linkEnd(tasks.find(t => t.name === 'A'))"), dates("B")))
    seed(chain()); pg.evaluate("() => { const a = tasks.find(t => t.name === 'A'); a.actualFinish = '2026-09-12'; cascadeSchedule(a.id); }")
    check("an actual finish on a Saturday: the successor still starts on a working day (Mon 14.09)", dates("B")[0] == "2026-09-14", dates("B"))
    # constraints
    seed([{"name": "K", "s": "2026-09-07", "e": "2026-09-09", "extra": {"constraintType": "SNET", "constraintDate": "2026-09-12"}}]); pg.evaluate("() => applyConstraints(tasks[0].id)")
    check("Start No Earlier Than a Saturday: the task starts the following Monday", dates("K") == ["2026-09-14", "2026-09-16"], dates("K"))
    # ================================================================ snapping what you type
    seed([A, {"name": "M", "s": "2026-09-07", "e": "2026-09-11", "mode": "manual", "extra": {"taskMode": "manual"}}])
    edit("A", "start", "2026-09-12")
    check("Start typed as a Saturday moves to Monday (an Auto task starts on a working day), with a toast", dates("A")[0] == "2026-09-14" and "working day" in pg.inner_text("#toastMsg"), (dates("A"), pg.inner_text("#toastMsg")))
    seed([A]); edit("A", "finish", "2026-09-13")
    check("Finish typed as a Sunday moves back to Friday", dates("A") == ["2026-09-07", "2026-09-11"], dates("A"))
    seed([{"name": "Mil", "s": "2026-09-07", "e": "2026-09-07", "extra": {"milestone": True}}]); edit("Mil", "start", "2026-09-13")
    check("a milestone typed onto a Sunday moves to Monday and stays one date", dates("Mil") == ["2026-09-14", "2026-09-14"], dates("Mil"))
    seed([{"name": "M", "s": "2026-09-07", "e": "2026-09-11", "extra": {"taskMode": "manual"}}])
    edit("M", "start", "12.09.2026")
    check("a MANUALLY scheduled task keeps a Saturday start exactly as typed", dates("M")[0] == "2026-09-12", dates("M"))
    # dialog
    seed([A])
    pg.evaluate("n => openTaskModal(tasks.find(t => t.name === n).id)", "A"); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(100)
    pg.fill("#taskStartInput", "2026-09-12"); pg.dispatch_event("#taskStartInput", "change")
    check("dialog: an Auto task's Start on a Saturday moves to Monday right away", pg.input_value("#taskStartInput") == "2026-09-14", pg.input_value("#taskStartInput"))
    pg.fill("#taskDurationInput", "6"); pg.dispatch_event("#taskDurationInput", "change")
    check("dialog: Duration 6 from Monday 14.09 -> Finish Monday 21.09; the duration field agrees", pg.input_value("#taskEndInput") == "2026-09-21" and pg.input_value("#taskDurationInput") == "6", (pg.input_value("#taskEndInput"), pg.input_value("#taskDurationInput")))
    pg.fill("#taskEndInput", "2026-09-19"); pg.dispatch_event("#taskEndInput", "change")
    check("dialog: Finish on a Saturday moves back to Friday 18.09 (duration 5)", pg.input_value("#taskEndInput") == "2026-09-18" and pg.input_value("#taskDurationInput") == "5", (pg.input_value("#taskEndInput"), pg.input_value("#taskDurationInput")))
    pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("...and saving keeps those dates", dates("A") == ["2026-09-14", "2026-09-18"], dates("A"))
    # adding a task
    pg.evaluate("() => { tasks.length = 0; project.newTaskMode = 'auto'; addTask(); closeTaskModal(); }"); pg.wait_for_timeout(300)
    check("a new Auto task starts on a working day (today, or the next working day)", pg.evaluate("() => { const t = tasks[0]; return isWorkDay(t.startDate) && t.startDate === nextWorkDay(todayStr()) && t.endDate === t.startDate; }"))
    pg.evaluate("() => { tasks.length = 0; project.newTaskMode = 'manual'; addTask(); closeTaskModal(); }"); pg.wait_for_timeout(300)
    check("a new MANUAL task starts today, whatever weekday that is", pg.evaluate("() => tasks[0].startDate === todayStr()"))
    pg.evaluate("() => { project.newTaskMode = 'auto'; }")
    # ================================================================ dragging on the Gantt
    seed([A]); pg.evaluate("() => { currentView = 'gantt'; zoom = 'week'; render(); }"); pg.wait_for_timeout(200)
    px = pg.evaluate("() => currentZoom().pxPerDay")
    def drag(mode, days):
        sel = ".gantt-bar" if mode == "move" else f".gantt-bar .resize-handle.{'right' if mode == 'right' else 'left'}"
        box = pg.locator(sel).first.bounding_box()
        x = box["x"] + (box["width"] / 2 if mode == "move" else 1); y = box["y"] + box["height"] / 2   # (the link handle covers the outer part of the right resize handle)
        pg.mouse.move(x, y); pg.mouse.down(); pg.mouse.move(x + days * px / 2, y); pg.mouse.move(x + days * px, y); pg.mouse.up(); pg.wait_for_timeout(200)
    drag("move", 5)
    check("dragging an Auto bar 5 calendar days (onto Saturday) lands on Monday and keeps its 5 working days: 14.09-18.09", dates("A") == ["2026-09-14", "2026-09-18"], dates("A"))
    seed([A]); pg.evaluate("() => { currentView = 'gantt'; render(); }"); pg.wait_for_timeout(200); drag("right", 1)
    check("resizing the end onto Saturday snaps back to Friday (no change)", dates("A") == ["2026-09-07", "2026-09-11"], dates("A"))
    seed([A]); pg.evaluate("() => { currentView = 'gantt'; render(); }"); pg.wait_for_timeout(200); drag("right", 3)
    check("resizing the end to Monday: 07.09-14.09 = 6 working days", dates("A") == ["2026-09-07", "2026-09-14"] and dur("A") == 6, dates("A"))
    seed([{"name": "M", "s": "2026-09-07", "e": "2026-09-11", "extra": {"taskMode": "manual"}}]); pg.evaluate("() => { currentView = 'gantt'; render(); }"); pg.wait_for_timeout(200); drag("move", 5)
    check("dragging a MANUAL bar moves it by the calendar days it was dragged: 12.09-16.09", dates("M") == ["2026-09-12", "2026-09-16"], dates("M"))
    # ================================================================ shading in the Gantt
    seed([A]); pg.evaluate("() => { currentView = 'gantt'; zoom = 'week'; render(); }"); pg.wait_for_timeout(200)
    n = pg.locator(".gantt-nonwork").count(); w = pg.evaluate("() => [...new Set([...document.querySelectorAll('.gantt-nonwork')].map(e => Math.round(parseFloat(e.style.width))))]")
    check("Week zoom: the days off are shaded, one band per weekend, two days wide", n >= 1 and w == [2 * px], (n, w))
    check("...the shading never intercepts the mouse", pg.evaluate("() => getComputedStyle(document.querySelector('.gantt-nonwork')).pointerEvents") == "none")
    pg.evaluate("() => { zoom = 'year'; render(); }"); pg.wait_for_timeout(150)
    check("Year zoom: no shading (1.5px a day would only be noise)", pg.locator(".gantt-nonwork").count() == 0)
    pg.evaluate("() => { zoom = 'week'; render(); }")
    # ================================================================ the dialog for the calendar
    pg.evaluate("() => { currentView = 'tasks'; render(); }"); pg.wait_for_timeout(100)
    pg.click("#planMenuBtn"); pg.wait_for_selector("#planMenu.open")
    check("the plan menu has 'Working calendar…' with the current setting next to it", "Mon–Fri" in pg.inner_text("#planCalendarItem") and "Working calendar" in pg.inner_text("#planCalendarItem"), pg.inner_text("#planCalendarItem"))
    pg.click("#planCalendarItem"); pg.wait_for_selector("#calendarModalBg.open"); pg.wait_for_timeout(100)
    checked = lambda: pg.evaluate("() => [...document.querySelectorAll('#calendarDays input:checked')].map(i => Number(i.value)).sort()")
    check("the dialog shows Mon-Sun as chips, Mon-Fri ticked, named after the plan", checked() == [1, 2, 3, 4, 5] and pg.locator("#calendarDays .cal-day").count() == 7 and pg.inner_text("#calendarPlanName") == "My Project" and [t.strip() for t in pg.locator("#calendarDays .cal-day").all_inner_texts()] == ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])
    pg.locator("#calendarDays .cal-day", has_text="Sat").click()
    pg.click("#calendarModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("adding Saturday and saving: the plan works Mon-Sat, stored with the plan, toast", pg.evaluate("() => project.workDays.join()") == "1,2,3,4,5,6" and "Mon–Sat" in pg.inner_text("#toastMsg") and pg.evaluate("() => calendarLabel()") == "Mon–Sat")
    seed([{"name": "S", "s": "2026-09-07", "e": "2026-09-12"}])
    check("...a Monday-Saturday task is now 6 working days", dur("S") == 6, dur("S"))
    check("...and it is saved with the plan file data", pg.evaluate("() => JSON.stringify(syncPayload().project.workDays)") == "[1,2,3,4,5,6]")
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(300)
    check("the calendar survives a reload", pg.evaluate("() => currentWorkDays().join()") == "1,2,3,4,5,6", pg.evaluate("() => currentWorkDays().join()"))
    pg.evaluate("() => { currentView = 'gantt'; zoom = 'week'; render(); }"); pg.wait_for_timeout(200)
    w = pg.evaluate("() => [...new Set([...document.querySelectorAll('.gantt-nonwork')].map(e => Math.round(parseFloat(e.style.width))))]")
    check("Mon-Sat: only Sundays are shaded (one day wide)", w == [px], w)
    pg.evaluate("() => { currentView = 'tasks'; render(); }")
    pg.click("#planMenuBtn"); pg.wait_for_selector("#planMenu.open"); pg.click("#planCalendarItem"); pg.wait_for_selector("#calendarModalBg.open"); pg.wait_for_timeout(100)
    check("reopening shows what was saved", checked() == [1, 2, 3, 4, 5, 6])
    pg.click("#calendarDays .cal-day >> nth=0"); pg.click("#calendarDays .cal-day >> nth=1"); pg.click("#calendarDays .cal-day >> nth=2"); pg.click("#calendarDays .cal-day >> nth=3"); pg.click("#calendarDays .cal-day >> nth=4"); pg.click("#calendarDays .cal-day >> nth=5")
    pg.click("#calendarModalBg .btn-primary"); pg.wait_for_timeout(150)
    check("unticking every day is refused: 'Pick at least one working day', dialog stays, nothing changes", "at least one" in pg.inner_text("#toastMsg") and pg.evaluate("() => document.getElementById('calendarModalBg').classList.contains('open')") and pg.evaluate("() => currentWorkDays().join()") == "1,2,3,4,5,6")
    check("the dialog has no preset buttons — only the seven day chips", pg.locator("#calendarModalBg .cal-presets").count() == 0 and pg.locator("#calendarDays .btn").count() == 0 and pg.locator("#calendarModalBg .modal-body .btn").count() == 2)   # (the two buttons are the holiday section's: Add public holidays, and Add a single one)
    for i in range(7): pg.click(f"#calendarDays .cal-day >> nth={i}")
    pg.click("#calendarModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("ticking all seven days stores them all; nothing is shaded any more", pg.evaluate("() => project.workDays.join()") == "0,1,2,3,4,5,6" and pg.evaluate("() => { currentView = 'gantt'; zoom = 'week'; render(); return document.querySelectorAll('.gantt-nonwork').length; }") == 0)
    seed([{"name": "E", "s": "2026-09-07", "e": "2026-09-13"}])
    check("with every day working, durations are calendar days again (Mon-Sun = 7)", dur("E") == 7)
    pg.evaluate("() => { currentView = 'tasks'; render(); }")
    pg.click("#planMenuBtn"); pg.wait_for_selector("#planMenu.open"); pg.click("#planCalendarItem"); pg.wait_for_selector("#calendarModalBg.open"); pg.wait_for_timeout(100)
    pg.click("#calendarDays .cal-day >> nth=5"); pg.click("#calendarDays .cal-day >> nth=6"); pg.click("#calendarModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("going back to Mon-Fri (untick Sat and Sun) removes the setting from the plan (the default is never stored)", pg.evaluate("() => project.workDays === undefined && JSON.stringify(syncPayload().project).includes('workDays') === false"))
    pg.click("#planMenuBtn"); pg.wait_for_selector("#planMenu.open"); pg.click("#planCalendarItem"); pg.wait_for_selector("#calendarModalBg.open"); pg.wait_for_timeout(100)
    pg.keyboard.press("Escape"); pg.wait_for_timeout(200)
    check("Escape closes the dialog without changing anything", not pg.evaluate("() => document.getElementById('calendarModalBg').classList.contains('open')") and pg.evaluate("() => calendarLabel()") == "Mon–Fri")
    # ================================================================ robustness
    check("a garbage setting in a file (strings, duplicates, out-of-range numbers) is cleaned up", pg.evaluate("() => { project.workDays = ['3', 3, 9, -1, 'x', 5, 5]; normalizeData(); const r = project.workDays.join(); project.workDays = []; normalizeData(); const e = project.workDays === undefined; project.workDays = [1,2,3,4,5]; normalizeData(); return r === '3,5' && e && project.workDays === undefined; }"))
    check("no console errors", not errors, errors)
    print("console errors/warnings:", errors); print(f"{sum(results)}/{len(results)} passed"); b.close()
