import io, json, os, tempfile, time
from playwright.sync_api import sync_playwright
import openpyxl
import os
URL = os.environ.get("MILESTONE_URL", "http://127.0.0.1:8937/milestone.html")
errors, results = [], []
def check(name, cond, detail=""):
    results.append(bool(cond)); print(("PASS  " if cond else "FAIL  ") + name + (f"   [{str(detail)[:400]}]" if not cond and detail else ""))
# A user's journey through the whole app, with real clicks: build a plan, structure it, link it, track it, look at it, share it.
with sync_playwright() as p:
    b = p.chromium.launch(headless=True)
    ctx = b.new_context(viewport={"width": 1600, "height": 900}, accept_downloads=True); ctx.add_init_script("delete window.showOpenFilePicker; delete window.showSaveFilePicker")
    pg = ctx.new_page(); pg.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e))); pg.on("console", lambda m: errors.append(m.text) if m.type in ("error", "warning") else None)
    pg.goto(URL); pg.wait_for_selector("#addTaskBtn"); pg.evaluate("() => localStorage.clear()"); pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(300)
    T = lambda n: pg.evaluate("n => { const t = tasks.find(x => x.name === n); return t ? JSON.parse(JSON.stringify(t)) : null; }", n)
    dates = lambda n: (lambda t: [t["startDate"], t["endDate"]])(T(n))
    rows = lambda: pg.locator("#gridRows .grid-row").count()
    hc = lambda: pg.evaluate("() => [...document.querySelectorAll('#gridHeader .col-filter-btn')].map(b => b.dataset.col)")
    def cell(name, col): return pg.locator(f".grid-row[data-id='{T(name)['id']}']").locator(":scope > div").nth(1 + hc().index(col))
    def rowbtn(name, title): pg.locator(f".grid-row[data-id='{T(name)['id']}']").hover(); pg.locator(f".grid-row[data-id='{T(name)['id']}'] .grid-actions button[title^='{title}']").click(); pg.wait_for_timeout(200)
    def select(name): pg.locator(f".grid-row[data-id='{T(name)['id']}']").click(position={"x": 25, "y": 10}); pg.wait_for_timeout(120)
    def focus_wait(): pg.wait_for_function("() => document.activeElement && document.activeElement.classList.contains('inline-edit')")
    def inline(name, col, value):
        target = lambda: pg.locator(f".grid-row[data-id='{T(name)['id']}'] .name-text") if col == "name" else cell(name, col)   # (a name is edited by clicking the text itself)
        target().click()
        try: pg.wait_for_selector(".inline-edit", timeout=1500)
        except Exception: target().click(); pg.wait_for_selector(".inline-edit")   # (the first click can land while the list is still re-rendering after a menu closed)
        focus_wait(); pg.fill(".inline-edit", value); pg.keyboard.press("Enter"); pg.wait_for_timeout(180)
    def add_task(name, start, end):   # through the dialog, as a user does
        pg.click("#addTaskBtn"); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(120)
        pg.fill("#taskNameInput", name); pg.fill("#taskStartInput", start); pg.dispatch_event("#taskStartInput", "change"); pg.fill("#taskEndInput", end); pg.dispatch_event("#taskEndInput", "change")
        pg.click("#taskModalBg .btn-primary"); pg.wait_for_selector("#taskModalBg:not(.open)"); pg.wait_for_timeout(150)
    toast = lambda: pg.inner_text("#toastMsg")

    # ============================================================ 1. an empty plan
    check("a fresh plan shows the empty state and a working Add Task button", "No tasks yet" in pg.inner_text("#gridRows") and pg.locator("#addTaskBtn").is_enabled())
    check("the toolbar buttons that need a task are disabled until one is selected", pg.is_disabled("#indentBtn") and pg.is_disabled("#deleteTaskBtn") and pg.is_disabled("#cloneTaskBtn"))
    # ============================================================ 2. building the plan (through the dialog)
    add_task("Kick-off", "2026-09-07", "2026-09-07"); add_task("Design", "2026-09-07", "2026-09-11"); add_task("Sketches", "2026-09-07", "2026-09-09"); add_task("Review", "2026-09-10", "2026-09-11"); add_task("Build", "2026-09-14", "2026-09-25"); add_task("Test", "2026-09-28", "2026-10-02")
    check("six tasks added through the dialog: six rows, in the order added (each below the previously selected one)", rows() == 6 and [t["name"] for t in pg.evaluate("() => visibleTaskList().map(v => v.task)")] == ["Kick-off", "Design", "Sketches", "Review", "Build", "Test"])
    check("their dates are what was typed", dates("Design") == ["2026-09-07", "2026-09-11"] and dates("Build") == ["2026-09-14", "2026-09-25"], (dates("Design"), dates("Build")))
    # ============================================================ 3. structure
    select("Sketches"); pg.click("#indentBtn"); pg.wait_for_timeout(150); select("Review"); pg.click("#indentBtn"); pg.wait_for_timeout(150)
    check("Indent makes Sketches and Review sub-tasks of Design (a group with a rollup: 07.09 to 11.09, WBS 2.1 / 2.2)", T("Sketches")["parentId"] == T("Design")["id"] and T("Review")["parentId"] == T("Design")["id"] and pg.evaluate("n => wbsCode(tasks.find(t => t.name === n).id)", "Review") == "2.2")
    pg.locator(f".grid-row[data-id='{T('Design')['id']}'] .chevron").click(); pg.wait_for_timeout(150)
    check("the chevron collapses the group (its two tasks are hidden), and expands it again", rows() == 4 and (pg.locator(f".grid-row[data-id='{T('Design')['id']}'] .chevron").click() or True) and pg.wait_for_timeout(150) is None and rows() == 6)
    pg.click("#collapseToggleBtn"); pg.wait_for_timeout(150); collapsed = rows(); pg.click("#collapseToggleBtn"); pg.wait_for_timeout(150)
    check("the header toggle steps through the outline (all collapsed -> all open)", collapsed == 4 and rows() == 6, (collapsed, rows()))
    # ============================================================ 4. dependencies (dialog) and scheduling
    pg.locator(f".grid-row[data-id='{T('Build')['id']}']").locator("> div").first.dblclick(); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(120)
    pg.click("#taskModalBg button:has-text('Add predecessor')"); pg.fill(".pred-id-input", str(pg.evaluate("() => taskDisplayId(tasks.find(t => t.name === 'Review').id)"))); pg.dispatch_event(".pred-id-input", "change")
    pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("Build depends on Review (FS): it starts the next working day after Review's finish and keeps its 10 working days", dates("Build") == ["2026-09-14", "2026-09-25"], dates("Build"))
    inline("Review", "end", "2026-09-16")
    check("Review's Finish moved to 16.09: Build (Auto) is pushed to start 17.09 and keeps its length (10 working days -> 30.09)", dates("Build") == ["2026-09-17", "2026-09-30"], dates("Build"))
    pg.locator(f".grid-row[data-id='{T('Test')['id']}']").locator("> div").first.dblclick(); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(120)
    pg.click("#taskModalBg button:has-text('Add predecessor')"); pg.fill(".pred-id-input", str(pg.evaluate("() => taskDisplayId(tasks.find(t => t.name === 'Build').id)"))); pg.dispatch_event(".pred-id-input", "change"); pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("...and Test follows Build (chain Review -> Build -> Test)", dates("Test")[0] == "2026-10-01", dates("Test"))
    # ============================================================ 5. inline editing
    pg.click("#columnsBtn"); pg.wait_for_selector("#columnsMenu.open"); pg.locator("#columnsMenu input[data-col='resource']").set_checked(True); pg.keyboard.press("Escape"); pg.wait_for_timeout(150)   # Resource is not shown by default
    inline("Kick-off", "resource", "Anna"); inline("Kick-off", "name", "Project kick-off")
    check("inline edits: Resource and Name (click, type, Enter)", T("Project kick-off")["resource"] == "Anna")
    inline("Test", "duration", "3")
    check("Duration 3 on Test -> 3 working days from its start", dates("Test") == ["2026-10-01", "2026-10-05"], dates("Test"))
    cell("Test", "start").click(); pg.wait_for_selector(".inline-edit"); pg.keyboard.press("Escape"); pg.wait_for_timeout(150)
    check("Escape cancels an inline edit without changing anything", pg.locator(".inline-edit").count() == 0 and dates("Test") == ["2026-10-01", "2026-10-05"])
    # ============================================================ 6. baseline, actuals, variance
    pg.click("#planMenuBtn"); pg.click("#planBaselineItem"); pg.wait_for_selector("#baselineModalBg.open"); pg.click("#baselineSetBtn"); pg.wait_for_timeout(250); pg.click("#baselineModalBg .modal-footer .btn >> text=Close"); pg.wait_for_timeout(150)
    check("Set baseline: every scheduled task keeps its dates as Baseline (groups roll up), toast with Undo", T("Build")["baselines"]["0"] == ["2026-09-17", "2026-09-30"] and "Baseline set" in toast())
    pg.click("#columnsBtn"); pg.wait_for_selector("#columnsMenu.open")
    for col in ("baselineStart", "startVariance", "finishVariance", "actualStart", "actualFinish"): pg.locator(f"#columnsMenu input[data-col='{col}']").set_checked(True)
    pg.keyboard.press("Escape"); pg.wait_for_timeout(150)
    inline("Sketches", "actualStart", "2026-09-08")
    check("recording an Actual Start (08.09): it becomes the Start, the task keeps its 3 working days, the variance columns show the slip", dates("Sketches") == ["2026-09-08", "2026-09-10"] and cell("Sketches", "startVariance").inner_text().strip() == "+1 day", (dates("Sketches"), cell("Sketches", "startVariance").inner_text()))
    inline("Sketches", "actualFinish", "2026-09-11")
    check("an Actual Finish completes the task (100%, Status Complete) and Finish Variance shows +2 days", T("Sketches")["progress"] == 100 and cell("Sketches", "finishVariance").inner_text().strip() == "+2 days" and "Complete" in pg.inner_text(f".grid-row[data-id='{T('Sketches')['id']}']"))
    # ============================================================ 7. calendar
    pg.click("#planMenuBtn"); pg.click("#planCalendarItem"); pg.wait_for_selector("#calendarModalBg.open"); pg.locator("#calendarDays .cal-day", has_text="Sat").click(); pg.click("#calendarModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("Working calendar: adding Saturday (Mon-Sat) is saved with the plan and shown in the plan menu", pg.evaluate("() => project.workDays.join()") == "1,2,3,4,5,6" and "Mon–Sat" in (pg.click("#planMenuBtn") or pg.inner_text("#planCalendarItem")))
    pg.keyboard.press("Escape")
    # ============================================================ 8. filters
    pg.click(".col-filter-btn[data-col='name']"); pg.wait_for_selector("#filterMenu.open"); pg.fill("#filterSearch", "Build"); pg.wait_for_timeout(120); pg.click("#filterOkBtn"); pg.wait_for_timeout(200)
    check("a column filter (Task Name: Build) leaves one row and shows a chip", rows() == 1 and pg.locator("#filterBar .filter-chip").count() == 1, (rows(), pg.locator("#filterBar .filter-chip").count()))
    pg.click("#filterBar >> text=Clear all"); pg.wait_for_timeout(200)
    check("'Clear all' brings every row back", rows() == 6)
    # ============================================================ 9. the Gantt view
    pg.click(".view-tab:has-text('Gantt')"); pg.wait_for_timeout(300)
    check("the Gantt view: the same list on the left (its own columns) next to the chart, one bar per scheduled task, baselines under them", pg.locator("#gridRows .grid-row").count() == 6 and pg.locator(".gantt-bar").count() >= 4 and pg.locator(".gantt-base").count() >= 4, (pg.locator(".gantt-bar").count(), pg.locator(".gantt-base").count()))
    check("...rows of the list and of the chart are level, the header heights equal", pg.evaluate("() => { const a = [...document.querySelectorAll('#gridRows .grid-row')].map(r => r.getBoundingClientRect().top), b = [...document.querySelectorAll('.gantt-row-bg')].map(r => r.getBoundingClientRect().top); return a.every((t, i) => Math.abs(t - b[i]) < .5) && document.getElementById('gridHeaderClip').getBoundingClientRect().height === document.getElementById('ganttHeader').getBoundingClientRect().height; }"))
    for z in ("Month", "Year", "Week"): pg.click(f"#zoomTabs .view-tab:has-text('{z}')"); pg.wait_for_timeout(150)
    check("the zoom tabs (Week / Month / Year) redraw the chart without errors", pg.locator(".gantt-bar").count() >= 4)
    bar = pg.locator(f".gantt-bar[data-id='{T('Test')['id']}']"); box = bar.bounding_box(); before = dates("Test")
    pg.mouse.move(box["x"] + box["width"] / 2, box["y"] + 10); pg.mouse.down(); pg.mouse.move(box["x"] + box["width"] / 2 + 14 * 7, box["y"] + 10, steps=6); pg.mouse.up(); pg.wait_for_timeout(250)
    check("dragging a bar reschedules the task by whole days (Test moved a week later, onto working days)", dates("Test") != before and pg.evaluate("n => isWorkDay(tasks.find(t => t.name === n).startDate)", "Test"), (before, dates("Test")))
    pg.click("#criticalPathBtn"); pg.wait_for_timeout(200); crit = pg.locator(".gantt-bar.critical").count(); pg.click("#criticalPathBtn"); pg.wait_for_timeout(150)
    check("the critical path button highlights the critical chain (and toggles off)", crit >= 1 and pg.locator(".gantt-bar.critical").count() == 0, crit)
    pg.click("#columnsBtn"); pg.wait_for_selector("#columnsMenu.open"); head = pg.inner_text("#columnsMenu .cols-head"); pg.locator("#columnsMenu input[data-col='progress']").set_checked(True); pg.keyboard.press("Escape"); pg.wait_for_timeout(150)
    check("Columns in the Gantt view edits the Gantt view's own set (the Tasks view is untouched)", "Gantt view" in head and "progress" in pg.evaluate("() => visibleTaskCols('gantt')") and "progress" in pg.evaluate("() => visibleTaskCols('tasks')") and pg.evaluate("() => visibleTaskCols('gantt').length") != pg.evaluate("() => visibleTaskCols('tasks').length"))
    pg.click(".view-tab:has-text('Tasks')"); pg.wait_for_timeout(200)
    # ============================================================ 10. row actions: clone, delete, undo
    n0 = pg.evaluate("() => tasks.length")
    rowbtn("Design", "Clone"); check("Clone copies a group with all its sub-tasks (Design + 2 tasks = 3 new tasks)", pg.evaluate("() => tasks.length") == n0 + 3 and T("Design (copy)") is not None)
    pg.click("#toastUndoBtn"); pg.wait_for_timeout(200); check("Undo removes the clone completely", pg.evaluate("() => tasks.length") == n0)
    rowbtn("Test", "Delete"); pg.wait_for_selector("#confirmModalBg.open"); pg.click("#confirmModalActionBtn"); pg.wait_for_timeout(200)
    check("Delete asks for confirmation, then removes the task and offers Undo", T("Test") is None and "deleted" in toast().lower())
    pg.click("#toastUndoBtn"); pg.wait_for_timeout(200); check("Undo brings the task back with its dependency on Build", T("Test") is not None and len(T("Test")["predecessors"]) == 1)
    # ============================================================ 11. dialog: milestone, constraint, custom field, colour
    pg.locator(f".grid-row[data-id='{T('Project kick-off')['id']}']").locator("> div").first.dblclick(); pg.wait_for_selector("#taskModalBg.open"); pg.wait_for_timeout(150)
    pg.check("#taskMilestoneInput"); pg.click("#taskModalBg .btn-primary"); pg.wait_for_timeout(200)
    check("marking a task as a milestone gives it one date", T("Project kick-off")["milestone"] and dates("Project kick-off")[0] == dates("Project kick-off")[1])
    # ============================================================ 12. share: Excel and JSON, import, backups
    pg.click("#dataMenuBtn"); pg.click("#dataMenu >> text=Export to Excel"); pg.wait_for_selector("#excelModalBg.open")
    with pg.expect_download() as dl: pg.click("#excelExportBtn")
    path = os.path.join(tempfile.mkdtemp(), "plan.xlsx"); dl.value.save_as(path); wb = openpyxl.load_workbook(path)
    check("Export to Excel: a workbook with the Tasks and Gantt sheets, one row per task, real dates", wb.sheetnames == ["Tasks", "Gantt"] and wb["Tasks"].max_row >= 4 + 6)
    pg.click("#dataMenuBtn"); 
    with pg.expect_download() as dl2: pg.click("#dataMenu >> text=Export JSON")
    jpath = os.path.join(tempfile.mkdtemp(), "plan.json"); dl2.value.save_as(jpath); data = json.load(open(jpath))
    check("Export JSON: all tasks, the project settings (working calendar, baselines) and tombstones", len(data["tasks"]) == 6 and data["project"]["workDays"] == [1, 2, 3, 4, 5, 6] and data["project"]["baselines"]["0"] and "deletedTaskIds" in data)
    pg.evaluate("() => { tasks.find(t => t.name === 'Build').name = 'Build (changed)'; save(); }")
    pg.click("#dataMenuBtn"); pg.set_input_files("#fileInput", jpath); pg.wait_for_selector("#importModalBg.open"); pg.click("#importModalBg button:has-text('Replace')"); pg.wait_for_timeout(400)
    if pg.locator("#confirmModalBg.open").count(): pg.click("#confirmModalActionBtn"); pg.wait_for_timeout(300)
    check("Import -> Replace restores the exported plan (the renamed task is back to 'Build')", T("Build") is not None and T("Build (changed)") is None, [t["name"] for t in pg.evaluate("() => tasks")])
    pg.click("#dataMenuBtn"); pg.click("#dataMenu .dropdown-item:has-text('Backups')"); pg.wait_for_selector("#backupsModalBg.open")
    check("Local backups: today's snapshot is listed", pg.locator("#backupsList .backup-row").count() >= 1)
    pg.keyboard.press("Escape"); pg.wait_for_timeout(150)
    # ============================================================ 13. plans
    pg.click("#planMenuBtn"); pg.click("#planNewItem"); pg.wait_for_selector("#planModalBg.open"); pg.fill("#planNameInput", "Second plan"); pg.click("#planSubmitBtn"); pg.wait_for_timeout(500)
    check("a new plan starts empty with its own name, default calendar and no baselines", pg.inner_text("#planBtnName") == "Second plan" and pg.evaluate("() => tasks.length === 0 && project.workDays === undefined && project.baselines === undefined"))
    pg.click("#planMenuBtn"); pg.locator(".plan-item", has_text="My Project").first.click(); pg.wait_for_timeout(500)
    check("switching back: the first plan is intact (six tasks, Mon-Sat calendar, baseline)", pg.evaluate("() => tasks.length") == 6 and pg.evaluate("() => calendarLabel()") == "Mon–Sat" and T("Build")["baselines"] is not None)
    pg.click("#planMenuBtn"); pg.click("#planRenameItem"); pg.wait_for_selector("#planModalBg.open"); pg.fill("#planNameInput", "Renamed"); pg.keyboard.press("Enter"); pg.wait_for_timeout(300)
    check("Rename plan updates the title and the switcher", pg.inner_text("#planBtnName") == "Renamed" and pg.title().startswith("Renamed"))
    # ============================================================ 14. look and feel, help, persistence
    pg.click("#themeToggleBtn"); pg.wait_for_timeout(200); dark = pg.evaluate("() => document.documentElement.getAttribute('data-theme')"); pg.click("#themeToggleBtn"); pg.wait_for_timeout(150)
    check("the theme toggle switches dark / light", dark == "dark" and pg.evaluate("() => document.documentElement.getAttribute('data-theme')") != "dark")
    pg.click("button[title='Help']"); pg.wait_for_selector("#helpModalBg.open"); ht = pg.evaluate("() => document.getElementById('helpModalBg').textContent"); pg.keyboard.press("Escape"); pg.wait_for_timeout(150)
    check("Help lists the main features (baselines, working calendar, working together on a file), Escape closes it", all(k in ht for k in ("Baselines and variance", "Working calendar", "Working together on one file")) and pg.locator("#helpModalBg.open").count() == 0)
    pg.click("button[title='Help']"); pg.wait_for_selector("#helpModalBg.open"); pg.wait_for_timeout(300)
    hs = pg.evaluate("() => { const m = document.querySelector('#helpModalBg .modal'); const panes = [...document.querySelectorAll('#helpModalBg .help-pane')]; return { kids: [...m.children].map(c => c.className.split(' ')[0]), tabs: document.querySelectorAll('#helpModalBg [role=tab]').length, panes: panes.length, visible: panes.filter(p => !p.hidden).length, sections: document.querySelectorAll('#helpModalBg .help-section-title').length, scrolls: panes.some(p => p.scrollHeight > p.clientHeight), footerIn: m.querySelector('.modal-footer') !== null }; }")
    check("the Help dialog is well-formed: header, a tabbed body (6 topics, one visible pane) and the footer inside the dialog", hs["kids"] == ["modal-header", "help-layout", "modal-footer"] and hs["tabs"] == 6 and hs["panes"] == 6 and hs["visible"] == 1 and hs["sections"] >= 12 and hs["footerIn"], hs)
    pg.click("#helpTab-scheduling"); pg.wait_for_timeout(100); ht2 = pg.inner_text("#helpPane-scheduling")
    pg.click("#helpTab-progress"); pg.wait_for_timeout(100); ht3 = pg.inner_text("#helpPane-progress")
    check("...it documents undo/redo (Getting started) and holidays (Calendar & progress)", "Undo and redo" in ht and "holidays" in ht3.lower(), (ht[:60], ht3[:60]))
    pg.keyboard.press("Escape"); pg.wait_for_timeout(150)
    pg.click("button[title='About']"); pg.wait_for_selector("#aboutModalBg.open"); pg.keyboard.press("Escape"); pg.wait_for_timeout(120)
    state = pg.evaluate("() => ({ tasks: tasks.length, view: currentView, cols: visibleTaskCols('tasks').join(), gcols: visibleTaskCols('gantt').join(), text: canonicalText() })")
    pg.reload(); pg.wait_for_selector("#addTaskBtn"); pg.wait_for_timeout(400)
    after = pg.evaluate("() => ({ tasks: tasks.length, view: currentView, cols: visibleTaskCols('tasks').join(), gcols: visibleTaskCols('gantt').join(), text: canonicalText() })")
    check("after a reload everything is exactly as it was: the plan (byte for byte), the view, both column sets", after == state, {k: (state[k], after[k]) for k in state if state[k] != after[k]})
    check("the whole journey produced no console errors or page errors", not errors, errors[:5])
    print("console errors/warnings:", errors[:5]); print(f"{sum(results)}/{len(results)} passed"); b.close()
